import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // App & Branding
    appTitle: "Jharkhand AR Safety Simulator",
    appSubtitle: "DGMS Statutory Vocational Certification System",
    portalWorker: "Worker AR Trainer",
    portalOfficer: "Site Safety Officer",
    portalDGMS: "DGMS Dhanbad Verifier",
    portalState: "State Nodal Analytics",
    sihTitle: "Smart India Hackathon 2026 • PS ID: 26041",
    sihAcademicBadge: "Academic Prototype",
    sihDisclaimer: "Smart India Hackathon 2026 (Problem Statement ID: 26041) — Technical Vocational Training & Safety Simulator. Not an official Government of Jharkhand or DGMS portal. Created solely for academic demonstration and hackathon evaluation.",
    skipToContent: "Skip to Main Content",
    screenReader: "Screen Reader",
    sihHelpdesk: "SIH Helpdesk: PS-26041",
    
    // Status & Utility Controls
    online: "Online Cloud Sync",
    offline: "Offline Local Store",
    voiceNarration: "Voice Narration",
    soundOn: "Audio Active",
    soundOff: "Audio Muted",
    speaking: "Speaking...",
    cloudSynced: "Cloud Synced",
    offlineCount: "Offline",
    syncNow: "Sync",
    syncing: "Syncing...",
    selectLanguage: "Select Language",
    activeMinerBadge: "Active Frontline Miner",
    activeAdminBadge: "Authenticated Regulatory Official",
    logOut: "Log Out",
    workerWorkspace: "Worker Workspace",
    adminWorkspace: "Regulatory Console",
    
    // Navigation Tabs
    tabModules: "AR Safety Drills",
    tabCertificates: "My Issued Passports (QR)",
    tabProfile: "Worker E-Identity",
    tabOfficer: "Safety Officer Roster",
    tabDgms: "DGMS Statutory Verifier",
    tabState: "State Nodal Analytics",

    // Offline Banner
    offlineNoticeTitle: "Statutory Field Notice:",
    offlineNoticeDesc: "Portal operating in offline mode. Vocational training modules, adaptive evaluations, and issued certificates are cached in local IndexedDB storage.",
    syncPendingTitle: "State Ledger Synchronization:",
    syncPendingDesc: "cached training record(s) queued for transmission to the central simulation compliance ledger.",
    syncSuccessTitle: "Ledger Synchronized:",
    syncSuccessDesc: "Field training records successfully transmitted and recorded in the State Compliance Ledger.",
    
    // Worker Login
    workerLoginHeader: "Khan Suraksha Training Portal",
    workerLoginSubheader: "Frontline Worker AR Vocational Safety Portal",
    workerLoginGuidanceTitle: "Worker Guidance:",
    workerLoginGuidanceText: "This portal provides practical AR safety simulations (fire extinguisher PASS technique and gas hazard response) and verifiable DGMS digital safety passports for mining and industrial workers.",
    workforceIdLabel: "Workforce ID / Mobile Number",
    workforceIdPlaceholder: "e.g. JH-WRK-001 or registered mobile",
    workerPinLabel: "Enter 4-Digit Safety PIN",
    workerPinHelp: "Default demo PIN is 1234",
    loginSubmitBtn: "Verify PIN & Access Portal",
    loginSubmitting: "Verifying Credentials...",
    demoMinersTitle: "Quick Select Demo Miner (Field Personnel):",
    demoMinersDesc: "Click any worker to auto-fill their credentials for demonstration:",
    statutoryComplianceNotice: "Statutory Competency System under Mines Act 1952 & Coal Mines Regulations 2017",
    
    // Admin Login
    adminLoginHeader: "Statutory Regulatory Administration",
    adminLoginSubheader: "Government of Jharkhand • Department of Mines & Geology",
    adminRegulatoryNotice: "Restricted Official Terminal. Access is monitored and cryptographically logged under DGMS statutory compliance frameworks. For hackathon evaluation, select an authorized role below.",
    adminRoleLabel: "Authority Role / Username",
    adminRolePlaceholder: "Select or enter admin username",
    adminPassLabel: "Master Authority Password",
    adminPassPlaceholder: "Enter regulatory password",
    captchaLabel: "Security CAPTCHA Verification",
    captchaPlaceholder: "Enter 5-character code",
    adminLoginBtn: "Sign In to Regulatory Console",
    adminLoggingIn: "Authenticating Authority...",
    roleSafetyOfficerTitle: "Site Safety Officer",
    roleSafetyOfficerDesc: "BCCL / CCL / ECL colliery site workforce enrollment and training tracking.",
    roleDgmsTitle: "DGMS Inspector (Dhanbad HQ)",
    roleDgmsDesc: "Statutory audit ledger, SHA-256 HMAC cryptographic certificate verification.",
    roleStateTitle: "State Nodal Officer",
    roleStateDesc: "Statewide mining analytics, district compliance metrics, and predictive safety KPIs.",
    adminDemoCredsNotice: "Demo Authority Credentials: username and password 'password123'",

    // Common Actions
    startSimulation: "Start AR Training",
    exitSimulation: "Exit Simulation",
    nextStep: "Next Step",
    previousStep: "Previous",
    finishAssessment: "Submit Assessment",
    viewCertificate: "View Certificate",
    downloadCertificate: "Download QR Certificate",
    printCertificate: "Print Certificate",
    savePdf: "Save as PDF",
    returnToPortal: "Return to Portal",
    certificateReadyTitle: "Statutory Vocational Safety Credential Ready",
    certificateReadySubtitle: "High-resolution A4 format • Official Mines Safety Record",
    
    // Worker Portal - E-Identity Card
    workerProfileTitle: "Worker E-Identity Profile",
    activeMinerStatus: "Statutory Active Miner",
    workforceCode: "Workforce Code",
    sectorLabel: "Sector",
    districtLabel: "District",
    activeCertsCounter: "Active DGMS Certs",
    mandatoryDrillsCounter: "Mandatory Drills",
    audioGuidanceBtn: "Audio Guidance",

    // Training Modules Section
    modulesSectionTitle: "Statutory Vocational AR Safety Modules",
    modulesSectionSubtitle: "Directorate General of Mines Safety (DGMS) prescribed practical camera-overlaid competency drills",
    certifiedBadge: "Certified",
    statutoryDrillBadge: "Statutory Drill",
    phase2Badge: "Phase 2 Pipeline",
    underDgmsSpec: "Under DGMS Specification",
    passThresholdLabel: "Benchmark:",
    
    // 5 Modules Details
    module1Title: "Fire & Explosion Response",
    module1Subtitle: "Exit identification, extinguisher PASS technique, and evacuation drill",
    module1Desc: "Interactive camera AR simulation practicing emergency retreat path verification, extinguisher tamper-seal removal, base aiming, squeeze trigger, and sweeping smother technique under CMR 136.",
    module2Title: "Gas Leak & Confined Space Protocol",
    module2Subtitle: "Methane (CH4), Carbon Monoxide (CO), PPE donning, and buddy signaling",
    module2Desc: "Simulated coal face atmospheric test, multi-gas detector thresholds calibration, positive-pressure SCBA oxygen mask donning, and statutory two-person lifeline buddy signaling.",
    module3Title: "Machinery & Moving-Part Safety",
    module3Subtitle: "Conveyor belt lock-out tag-out (LOTO), roller pinch points, and emergency pull cords",
    module3Desc: "Virtual mechanical maintenance drill demonstrating power isolation padlocking, emergency trip wire activation, and conveyor roller nip guard compliance under DGMS Circular 2026.",
    module4Title: "Electrical & Blasting Clearance",
    module4Subtitle: "Flameproof enclosure inspection, explosive magazine handling, and shot-firing cordon",
    module4Desc: "Hazard inspection simulation covering FLP electrical switchgear gap gauges, detonator transport statutory protocol, and 300-metre blasting shelter clearance verification.",
    module5Title: "PPE Compliance & Induction",
    module5Subtitle: "Mandatory hard hat, steel-toe boots, metatarsal guards, and dust respirator donning",
    module5Desc: "Computer vision and AR alignment check ensuring mining helmet with cap lamp, high-visibility reflective harness, ear defenders, and safety footwear meet DGMS induction standards.",
    
    // Passports / Certificates Section
    passportsSectionTitle: "Verified Vocational Safety Passports (Simulation Records)",
    passportsSectionSubtitle: "Cryptographically signed records benchmarked against Mines Act 1952 & DGMS vocational training standards.",
    certNumberLabel: "Certificate Number",
    statutoryValidityLabel: "Statutory Validity:",
    noPassportsTitle: "No Passports Issued Yet",
    noPassportsDesc: "Complete the hands-on AR Fire Extinguisher or Methane Gas drill above, score ≥ 75% on the DGMS safety assessment, and your verified digital passport will automatically appear here and sync to the regulatory audit ledger.",
    startDrillCta: "Start an AR Drill Now",

    // AR Fire PASS Steps
    fireHudTitle: "DGMS STATUTORY SIMULATION • CMR REG. 136 (PASS DRILL)",
    emergencyExitSign: "EMERGENCY SHAFT ESCAPE WAY (25m) →",
    tapToLockAim: "TAP BASE TO LOCK NOZZLE AIM",
    passStep0Title: "Step 0: Verify Emergency Retreat Path",
    passStep0Desc: "Identify the green lighted escape shaft waypoint behind you. Ensure retreat path is clear before engaging.",
    passStep0Btn: "Retreat Route Verified: Advance →",
    passP_title: "Step 1: Pull the Safety Pin",
    passP_desc: "Break the tamper seal and pull the safety locking pin from the valve handle.",
    passP_btn: "Pull Safety Locking Pin →",
    passA_title: "Step 2: Aim Low at Fire Base",
    passA_desc: "Direct the discharge nozzle directly at the base and fuel source of the flames, never into smoke.",
    passA_btn: "Aim Locked at Fuel Base →",
    passS1_title: "Step 3: Squeeze the Lever",
    passS1_desc: "Depress the handle to release pressurized dry chemical extinguishing foam.",
    passS1_btnHold: "Hold Lever to Discharge Foam",
    passS1_btnRelease: "Release Lever",
    passS2_title: "Step 4: Sweep Side to Side",
    passS2_desc: "Sweep the nozzle horizontally covering the fire perimeter until completely smothered.",
    passS2_btn: "Sweeping Across Fire Base...",
    fireCompleteTitle: "Fire Smothered & Extinguished!",
    fireCompleteDesc: "You have completed the statutory PASS drill with verified technique. Proceed to the safety decision assessment.",
    fireCompleteBtn: "Proceed to Competency Assessment →",

    // AR Gas Module Steps
    gasHudTitle: "STATUTORY MULTI-GAS DETECTOR",
    gasDetectTitle: "Step 1: Atmospheric Gas Monitoring",
    gasDetectDesc: "Calibrate 4-gas detector. Check Methane (CH4 < 1.25%), CO (< 50 ppm), and Oxygen (19.5% - 23.5%).",
    gasDetectBtn: "Simulate Coal Face Gas Inflow Test →",
    gasAlarmTitle: "STATUTORY ALARM: CMR REGULATION 142 EXCEEDED",
    gasAlarmDesc: "Methane level has exceeded statutory explosive threshold (1.25%). Do NOT advance without certified Level-A Positive-Pressure Breathing Apparatus.",
    gasAlarmBtn: "Acknowledge Alarm & Don SCBA →",
    gasPpeTitle: "Step 2: Mandatory PPE Donning",
    gasPpeDesc: "Equip Self-Contained Breathing Apparatus (SCBA), anti-static helmet with cap lamp, and lifeline harness.",
    gasPpeBtn: "Confirm PPE Donning & Cylinder Seal →",
    gasBuddyTitle: "Step 3: Two-Person Buddy Signaling",
    gasBuddyDesc: "Establish visual and radio contact with standby buddy before crossing confined space threshold.",
    gasBuddyBtn: "Confirm 2-Way Radio Contact with Buddy →",
    gasCompleteTitle: "Gas Hazard Secured & Evacuation Verified",
    gasCompleteDesc: "All statutory atmospheric thresholds and buddy protocols complied with under DGMS guidelines.",
    gasCompleteBtn: "Proceed to Competency Assessment →",
    sensorOk: "OK",
    sensorCritical: "CRITICAL",
    sensorToxic: "TOXIC",
    sensorDeficient: "DEFICIENT",

    // Scenario Quiz
    quizHeader: "DGMS Statutory Decision Assessment",
    questionCounter: "Question",
    ofLabel: "of",
    complianceBenchmarkNotice: "Mines Safety Compliance Benchmark: 75%",
    selectAnswerPrompt: "Please select an answer option to proceed",
    submitDecisionBtn: "Submit Decision",
    nextQuestionBtn: "Next Question →",
    quizPassedTitle: "DGMS Statutory Assessment: PASSED",
    quizFailedTitle: "Competency Standard Not Met",
    quizPassedDesc: "Candidate has satisfied statutory safety decision benchmarks under Mines Act 1952. Cryptographic QR certificate is being generated.",
    quizFailedDesc: "Candidate scored below the mandatory 75% DGMS passing benchmark. Review statutory emergency instructions and retake the simulation drill.",
    scoreAccuracyLabel: "Decision Accuracy",
    scoreTechniqueLabel: "AR Technique Score",
    scoreEvaluationLabel: "Final Evaluation",
    verifiedForIssuance: "✓ Verified for Statutory Certificate Issuance",
    retakeDrillBtn: "Retake Vocational Drill",
    generateCertBtn: "Generate & View Certificate",
    voiceCorrect: "Correct decision!",
    voiceIncorrect: "Incorrect. Review the DGMS regulatory rationale.",

    // Safety Officer Dashboard
    officerDashboardTitle: "Site Safety Officer Workforce Roster",
    officerSiteSubtitle: "Monitoring tribal language preferences, literacy indicators, and active statutory safety certifications",
    enrolWorkerBtn: "Enrol New Frontline Worker",
    kpiTotalMiners: "Registered Workforce",
    kpiCertifiedRate: "Statutory Compliance",
    kpiPendingDrills: "Pending Refreshers",
    kpiTribalWorkforce: "Tribal Language Users",
    searchPlaceholder: "Search by Worker Name or ID...",
    filterAllCohorts: "All Training Cohorts",
    thWorkerId: "Worker ID",
    thNameDesig: "Name & Designation",
    thSite: "Colliery Site",
    thLanguage: "Tribal Language",
    thStatus: "Safety Status",
    thCerts: "Certifications",
    thActions: "Actions",
    enrolModalTitle: "Enrol New Frontline Worker",
    enrolModalDesc: "Register a miner under DGMS vocational training standards with language preference.",
    fieldName: "Full Name",
    fieldNamePlaceholder: "e.g. Birsa Hansda",
    fieldLanguage: "Primary Language",
    fieldDesignation: "Workforce Designation",
    fieldDesignationPlaceholder: "e.g. Underground Driller",
    fieldMobile: "Registered Mobile Number",
    fieldCohort: "Training Cohort",
    submitEnrolBtn: "Enrol Miner",
    cancelBtn: "Cancel",

    // DGMS Inspector Portal
    dgmsHeaderTitle: "Directorate General of Mines Safety (DGMS)",
    dgmsHeaderSubtitle: "Statutory Audit & Verification Terminal • Dhanbad HQ",
    searchLedgerTitle: "Cryptographic Certificate Verification Terminal",
    searchLedgerDesc: "Enter a SHA-256 HMAC Certificate Hash or Certificate ID to inspect the authentic state ledger record:",
    searchHashPlaceholder: "Enter SHA-256 Hash or Certificate ID (e.g. CERT-JH-2026-10000)",
    verifyBtn: "Verify Integrity",
    kpiAuditedMines: "Audited Colliery Sites",
    kpiCryptoPassports: "Digital Safety Passports",
    kpiLedgerIntegrity: "Ledger Integrity Check",
    kpiIntegrityStatus: "100% SHA-256 Validated",
    kpiViolations: "Non-Compliance Flagged",
    thCertId: "Certificate ID",
    thWorker: "Worker Code & Name",
    thModule: "Safety Module",
    thScore: "Score",
    thIssueDate: "Issue Date",
    thLedgerHash: "Ledger Hash (HMAC-SHA256)",
    thAuditStatus: "Statutory Status",
    btnInspect: "Inspect Record",
    modalAuditTitle: "DGMS Statutory Ledger Inspection",
    modalAuditDesc: "Cryptographic proof and worker compliance integrity verified against Dhanbad Central Server.",
    tamperProofValid: "TAMPER-PROOF SIGNATURE VERIFIED",
    btnClose: "Close",

    // State Nodal Dashboard
    stateHeaderTitle: "Department of Mines & Geology • Government of Jharkhand",
    stateHeaderSubtitle: "Statewide Mining Vocational Safety & AR Training Analytics",
    kpiTotalWorkforce: "Total Enrolled Workforce",
    kpiStateCompliance: "Statewide Compliance Rate",
    kpiDrillsCompleted: "AR Training Drills Completed",
    kpiIncidentIndex: "Safety & Incident Prevention Index",
    chartDistrictTitle: "District-Wise Compliance Benchmark",
    chartLanguageTitle: "Tribal Language Distribution in AR Training",
    chartModuleTitle: "Module-Wise Competency Mastery",
    thDistrict: "District",
    thSector: "Major Mining Sector",
    thMinesCount: "Active Mines/Plants",
    thEnrolledMiners: "Enrolled Miners",
    thDistrictRate: "Compliance Rate",
    thDistrictStatus: "Statutory Status",
    exportReportBtn: "Download Comprehensive State Report (CSV / PDF)",

    // Global Footer
    footerLinkHome: "Home",
    footerLinkSimulator: "Simulator Info",
    footerLinkCurriculum: "Curriculum Model",
    footerLinkRti: "RTI Disclosures",
    footerLinkEvaluation: "Evaluation Team",
    footerLinkActs: "Acts & Rules",
    footerLinkSafety: "Safety Framework",
    footerLinkScreenReader: "Screen Reader Access",
    footerLinkOfficialLogin: "Official Sign-In",
    footerDeptTitle: "Government of Jharkhand • Department of Mines & Geology",
    footerDeptDesc: "Collaborative vocational safety simulator engineered under DGMS vocational guidelines to empower frontline tribal colliery and mineral workers.",
    footerDgmsTitle: "Statutory Regulatory Standards",
    footerDgmsDesc: "Benchmarked against Mines Act 1952, Coal Mines Regulations 2017, and DGMS Circulars for zero fatal incidents.",
    footerSihTitle: "Smart India Hackathon 2026 Academic Safe Harbor",
    footerSihDesc: "Technical prototype for Problem Statement 26041. All data and certificates generated are for academic evaluation.",
    footerCopyright: "© 2026 Government of Jharkhand & Directorate General of Mines Safety (DGMS). Technical Prototype created for Smart India Hackathon 2026.",

    // Audio Prompts
    audioPullPin: "Pull the safety pin from the extinguisher now.",
    audioAimBase: "Aim the nozzle at the bottom of the fire.",
    audioSqueezeLever: "Squeeze the lever firmly to discharge foam.",
    audioSweepFire: "Sweep left and right across the fire.",
    audioGasAlarm: "Warning! Gas threshold exceeded. Don oxygen mask immediately!",
    audioBuddyConfirm: "Confirm buddy radio signal before entering the tunnel.",

    // Additional Gas Module keys
    gasHudAuditNotice: "DGMS STATUTORY SENSOR: ATMOSPHERIC GAS AUDIT",
    gasAlarmNotice: "DGMS DANGER: CONFINED GAS THRESHOLD EXCEEDED (CMR 142)",
    gasHeadingLabel: "DGMS CONFINED COAL SEAM HEADING #3 • ATMOSPHERIC GAS SENSORS ACTIVE",
    gasMethaneLimit: "CH₄ (DGMS <1.25%):",
    gasCoLimit: "CO (DGMS <50ppm):",
    gasOxygenLimit: "O₂ (DGMS 19.5-21%):",
    gasPpeVerifyPrompt: "Verify each mandatory personal protective item under Mines Act 1952:",
    gasPpeMask: "1. Positive-Pressure SCBA Oxygen Mask",
    gasPpeFitMask: "[Tap to Fit Mask]",
    gasPpeHelmet: "2. Antistatic Helmet with Intrinsically Safe LED Lamp",
    gasPpeLockHelmet: "[Tap to Lock Helmet]",
    gasPpeHarness: "3. Full-Body Safety Harness with Retrievable Lifeline",
    gasPpeAttachLifeline: "[Tap to Attach Lifeline]",
    gasPpeProceedBtn: "PPE Verified • Proceed to Buddy Communication Check →",
    gasPpeRequiredPrompt: "Fit All 3 Mandatory Items to Proceed",
    gasBuddyReqPrompt: "Mines Act Section 22 requires standby surface buddy communication verification:",
    gasBuddyRadio: "Radio Comms Frequency Check (Channel 4 Mining Band)",
    gasBuddyCheckRadio: "[Check Signal]",
    gasBuddyLifeline: "Lifeline Tug Protocol (2-Tugs = Normal, 3-Tugs = Emergency)",
    gasBuddyConfirmLifeline: "[Confirm Tug]",
    gasBuddyRequiredPrompt: "Complete Buddy Protocol to Continue",
    gasProtocolSuccessVoice: "Protocol verified. Confined space entry approved.",

    // Additional Scenario Quiz keys
    quizAssessmentTitle: "DGMS STATUTORY COMPETENCY ASSESSMENT",
    quizPaperSub: "Mines Act 1952 • Examination Paper",
    quizCorrectDecision: "Correct Regulatory Decision",
    quizViolation: "DGMS Safety Violation",
    quizViewResultsBtn: "View Evaluation Results →",
    quizNextBtn: "Next Question →",
    quizSubmitBtn: "Submit Answer & Verify Decision →",

    // Certificate Top Bar keys
    certActionBarTitle: "Statutory Vocational Safety Credential Ready",
    certA4Format: "High-resolution A4 format",
    certOfficialRecord: "Official Mines Safety Record",
    saveAsPdf: "Save as PDF",

    // Safety Officer Dashboard keys
    officerStationTitle: "Statutory Supervisory Station",
    officerDistrict: "District",
    officerSector: "Sector",
    officerSupervisoryOfficer: "Supervisory Officer",
    officerStationSub: "DGMS Statutory Training Station #4",
    officerOnboardRecruit: "Onboard New Recruit",
    officerCohortBatch: "Training Cohort Batch",
    officerEnrolledMiners: "Enrolled",
    officerMinersLabel: "miners",
    officerCertifiedMiners: "Certified",
    officerRosterTitle: "Frontline Workforce Roster & DGMS Certification Status",
    officerRosterSubtitle: "Monitoring tribal language preferences, literacy indicators, and active statutory safety certifications",
    officerSearchPlaceholder: "Search by worker name or ID...",
    officerAllCohorts: "All Training Cohorts",
    officerThWorkerCode: "Worker Code",
    officerThFullName: "Full Name",
    officerThTribalLang: "Tribal Language",
    officerThLiteracy: "Literacy",
    officerThDesignation: "Designation",
    officerThActiveCerts: "Active Certs",
    officerThStatus: "Statutory Status",
    officerCompliantBadge: "DGMS Compliant",
    officerTrainingDueBadge: "Training Due",
    officerDrillsCount: "drill(s)",
    officerBestScore: "Best",
    officerModalTitle: "Onboard Frontline Tribal Recruit",
    officerModalSubtitle: "Register recruit into colliery for camera-based AR training.",
    officerFieldFullName: "Full Name (with Tribal Surname):",
    officerFieldPrimaryLang: "Primary Language:",
    officerFieldDesignation: "Designation:",
    officerFieldContact: "Contact Phone Number:",
    officerFieldAssignCohort: "Assign to Training Cohort:",
    officerBtnCancel: "Cancel",
    officerBtnSubmitEnroll: "Enroll Worker & Assign AR Modules",

    // DGMS Portal keys
    dgmsConsoleBadge: "Regulatory Simulation Console",
    dgmsBenchmarkSub: "DGMS Standards Benchmark Console • Dhanbad Regulatory Framework",
    dgmsLedgerTitle: "Mines Act 1952 Compliance Ledger (DGMS Regulatory Simulation)",
    dgmsAuditorLabel: "Simulated Auditor / Inspector",
    dgmsBenchmarkRef: "Regulatory Benchmark Ref: DGMS/S&T/Circular-2026/041",
    dgmsExportCsv: "Export Statutory Audit Log (CSV)",
    dgmsScannerTitle: "Live On-Site QR Certificate Verifier & Anti-Forgery Scanner",
    dgmsScannerDesc: "Scan physical worker card QR code or paste Certificate ID / SHA-256 HMAC hash to verify ledger authenticity in real-time",
    dgmsInputPlaceholder: "Paste QR Hash (e.g. bb44da...) or Certificate ID (e.g. CERT-JH-2026-10004)...",
    dgmsVerifying: "Querying DGMS Ledger...",
    dgmsVerifyBtn: "Verify Authenticity →",
    dgmsTestValid: "Test Valid Cert",
    dgmsTestForgery: "Test Forgery Check",
    dgmsVerifiedAuthentic: "VERIFIED AUTHENTIC: STATUTORY DGMS COMPLIANT",
    dgmsFraudDetected: "RECORD NOT FOUND OR FRAUDULENT FORGERY DETECTED",
    dgmsVerifiedDetail: "Cryptographic SHA-256 HMAC digital signature validated against state ledger. Zero data tampering detected.",
    dgmsFraudDetail: "The submitted QR hash does not match records or has been altered.",
    dgmsWorkerDetails: "Worker Details",
    dgmsMineFacility: "Mine Facility Site",
    dgmsModuleCompetency: "Module Competency",
    dgmsValidityWindow: "Statutory Validity Window",
    dgmsPassedTag: "Score: {score}% (PASSED)",
    dgmsExpiresLabel: "Expires",
    dgmsRefresherDays: "day(s) until mandatory refresher",
    dgmsViewPrintCert: "View & Print Certificate",
    dgmsAuditRegisterTitle: "Mines Act, 1952 Statutory Audit Register",
    dgmsAuditRegisterDesc: "Mandatory digital registry of all issued competency certificates with cryptographic hashes",
    dgmsFilterSector: "Filter by Sector:",
    dgmsSectorAll: "All Industrial Sectors",
    dgmsSectorCoal: "Coal Mining (BCCL / CCL)",
    dgmsSectorSteel: "Steel Processing (SAIL / Tata)",
    dgmsSectorMica: "Mica Beneficiation (Koderma / Giridih)",
    dgmsThCertId: "Certificate ID",
    dgmsThWorkerCode: "Worker Code",
    dgmsThWorkerName: "Worker Name",
    dgmsThMineSite: "Mine / Plant Site",
    dgmsThDistrict: "District",
    dgmsThScore: "Score",
    dgmsThIssueDate: "Issue Date",
    dgmsThExpiryDate: "Expiry Date",
    dgmsThStatus: "Statutory Status",
    dgmsThVerify: "Verify",
    dgmsBtnAudit: "Audit",
    dgmsBtnPrint: "Print",
    dgmsClosePreview: "✕ Close Inspector Preview",

    // State Nodal Dashboard keys
    stateConsoleBadge: "State Nodal Analytics",
    stateConsoleSub: "Academic Simulation Console • Modeled on Dept. of Mines & Geology (Govt. of Jharkhand)",
    stateMainTitle: "Jharkhand Industrial Mine Safety — State Analytics & Compliance Simulation",
    stateOfficerLine: "Simulated State Nodal Officer",
    stateSandboxNotice: "Technical Evaluation Sandbox • Real-Time Regulatory Metrics",
    stateFrameworkTag: "Statutory Framework: Mines Act 1952 (DGMS Circulars)",
    stateKpiCertified: "Total Workers Certified",
    stateKpiGrowth: "↑ 18.4% month-over-month",
    stateKpiPassRate: "Overall Pass Rate",
    stateKpiDgmsBenchmark: "DGMS Benchmark: 75%",
    stateKpiActiveSites: "Active Mining Sites",
    stateKpiUnits: "Coal, Steel & Mica units",
    stateKpiRefresherDue: "Refresher Due (<30d)",
    stateKpiNoticeIssued: "Notice issued to site officers",
    stateChart1Title: "Weekly Certification Volume by District",
    stateChart1Sub: "Training progression across Dhanbad, Bokaro, Ramgarh & Koderma",
    stateChart2Title: "Tribal Language Distribution in AR Training",
    stateChart2Sub: "Breakdown of voiceover & script usage among frontline workers",
    stateRadarTitle: "Statutory 30-Day Certificate Expiry Early Warning Radar",
    stateRadarSub: "Mines Act 1952 mandates annual refresher training. Workers expiring within 30 days are flagged below.",
    stateActionRequired: "Action Required by Site Supervisors",
    stateThCertId: "Certificate ID",
    stateThWorkerCode: "Worker Code",
    stateThWorkerName: "Worker Name",
    stateThContactPhone: "Contact Phone",
    stateThMineSite: "Mine Site",
    stateThIssueDate: "Issue Date",
    stateThExpiryDate: "Statutory Expiry",
    stateThStatus: "Status",
    stateRefresherDueBadge: "⚠ Refresher Due",
    stateAllCompliant: "All statutory certifications are currently within their compliant validity window.",

    // Extended Footer keys
    footerDeptTitleText: "Smart India Hackathon 2026 (PS ID: 26041)",
    footerDeptSubText: "AR Vocational Mining Safety Simulation Engine",
    footerDeptBodyText: "Academic technical prototype developed for Smart India Hackathon 2026. Modeled on the vocational training curriculum of the Department of Mines & Geology (Govt. of Jharkhand) and statutory benchmarks of the Mines Act, 1952 and DGMS guidelines.",
    footerStandardsTitleText: "Benchmarked Standards & Guidelines",
    footerStd1Text: "• Directorate General of Mines Safety (DGMS) Safety Criteria",
    footerStd2Text: "• Mines Act, 1952 & Factories Act, 1948 Competency Metrics",
    footerStd3Text: "• Smart India Hackathon 2026 — Problem Statement ID: 26041",
    footerStd4Text: "• Guidelines for Indian Government Websites (GIGW 3.0 / WCAG 2.1 AA)",
    footerDevTitleText: "Development & Safe Harbor Provenance",
    footerDevByText: "Developed by SIH 2026 Team (Problem Statement ID: 26041)",
    footerDevSubText: "Educational & Research Prototype for Mining & Steel Safety Training",
    footerDrillCountText: "Simulated Workforce Drill Count:",
    footerLegalDisclaimerText: "Legal Disclaimer & Fair Dealing Notice: This platform is an independent educational and technical simulation prototype created for the Smart India Hackathon 2026 (Problem Statement ID: 26041). It is NOT an official government portal and is not operated by or formally affiliated with the Government of Jharkhand, Directorate General of Mines Safety (DGMS), or National Informatics Centre (NIC).",
    footerCopyrightNoticeText: "All statutory names, insignia representations, and regulatory benchmarks are referenced solely for competition evaluation and academic demonstration under the Fair Dealing provisions of Section 52 of the Indian Copyright Act, 1957."
  },

  hi: {
    // App & Branding
    appTitle: "झारखंड एआर सुरक्षा सिम्युलेटर",
    appSubtitle: "डीजीएमएस वैधानिक व्यावसायिक प्रमाणन प्रणाली",
    portalWorker: "श्रमिक एआर प्रशिक्षण",
    portalOfficer: "साइट सुरक्षा अधिकारी",
    portalDGMS: "डीजीएमएस धनबाद सत्यापन",
    portalState: "राज्य नोडल विश्लेषिकी",
    sihTitle: "स्मार्ट इंडिया हैकाथॉन 2026 • समस्या पहचान: 26041",
    sihAcademicBadge: "शैक्षणिक प्रोटोटाइप",
    sihDisclaimer: "स्मार्ट इंडिया हैकाथॉन 2026 (प्रॉब्लम स्टेटमेंट आईडी: 26041) — तकनीकी व्यावसायिक प्रशिक्षण एवं सुरक्षा सिम्युलेटर। यह झारखंड सरकार या डीजीएमएस का आधिकारिक पोर्टल नहीं है। केवल शैक्षणिक प्रदर्शन हेतु निर्मित।",
    skipToContent: "मुख्य सामग्री पर जाएं",
    screenReader: "स्क्रीन रीडर",
    sihHelpdesk: "एसआईएच हेल्पडेस्क: PS-26041",
    
    // Status & Utility Controls
    online: "ऑनलाइन क्लाउड सिंक",
    offline: "ऑफ़लाइन स्थानीय संग्रह",
    voiceNarration: "आवाज़ मार्गदर्शन",
    soundOn: "ऑडियो सक्रिय",
    soundOff: "ऑडियो बंद",
    speaking: "बोल रहा है...",
    cloudSynced: "क्लाउड से जुड़ा",
    offlineCount: "ऑफ़लाइन",
    syncNow: "सिंक करें",
    syncing: "सिंक जारी...",
    selectLanguage: "भाषा चुनें",
    activeMinerBadge: "सक्रिय फ्रंटलाइन खनिक",
    activeAdminBadge: "प्रमाणित नियामक अधिकारी",
    logOut: "लॉग आउट",
    workerWorkspace: "कामगार कार्यक्षेत्र",
    adminWorkspace: "नियामक कंसोल",
    
    // Navigation Tabs
    tabModules: "एआर सुरक्षा सिमुलेशन",
    tabCertificates: "प्रमाणित डिजिटल पासपोर्ट",
    tabProfile: "कामगार ई-पहचान पत्र",
    tabOfficer: "सुरक्षा अधिकारी रोस्टर",
    tabDgms: "डीजीएमएस धनबाद सत्यापन",
    tabState: "राज्य नोडल विश्लेषिकी",

    // Offline Banner
    offlineNoticeTitle: "वैधानिक क्षेत्रीय सूचना:",
    offlineNoticeDesc: "पोर्टल ऑफ़लाइन मोड में संचालित है। प्रशिक्षण मॉड्यूल, मूल्यांकन एवं जारी प्रमाण पत्र स्थानीय IndexedDB में सुरक्षित संग्रहीत हैं।",
    syncPendingTitle: "राज्य लेजर सिंक्रोनाइज़ेशन:",
    syncPendingDesc: "प्रशिक्षण रिकॉर्ड केंद्रीय अनुपालन लेजर में प्रेषित होने हेतु कतार में हैं।",
    syncSuccessTitle: "लेजर सिंक्रोनाइज़ हुआ:",
    syncSuccessDesc: "क्षेत्रीय प्रशिक्षण रिकॉर्ड केंद्रीय राज्य अनुपालन लेजर में सफलतापूर्वक दर्ज कर दिए गए हैं।",
    
    // Worker Login
    workerLoginHeader: "खान सुरक्षा प्रशिक्षण पोर्टल",
    workerLoginSubheader: "फ्रंटलाइन कामगार एआर व्यावसायिक सुरक्षा पोर्टल",
    workerLoginGuidanceTitle: "कामगार निर्देश:",
    workerLoginGuidanceText: "यह पोर्टल खदान एवं उद्योग कामगारों के लिए व्यावहारिक एआर सुरक्षा सिमुलेशन (अग्निशामक PASS तकनीक एवं गैस रिसाव) एवं DGMS डिजिटल सुरक्षा पासपोर्ट प्रदान करता है।",
    workforceIdLabel: "कामगार कोड / पंजीकृत मोबाइल नंबर",
    workforceIdPlaceholder: "उदा. JH-WRK-001 अथवा मोबाइल नंबर",
    workerPinLabel: "4-अंकीय सुरक्षा पिन दर्ज करें",
    workerPinHelp: "डिफ़ॉल्ट डेमो पिन 1234 है",
    loginSubmitBtn: "पिन सत्यापित करें एवं पोर्टल में प्रवेश करें",
    loginSubmitting: "पहचान सत्यापित हो रही है...",
    demoMinersTitle: "डेमो कामगार का त्वरित चयन (क्षेत्रीय कर्मी):",
    demoMinersDesc: "प्रतियोगिता परीक्षण के लिए किसी भी कामगार पर क्लिक करके क्रेडेंशियल स्वतः भरें:",
    statutoryComplianceNotice: "खान अधिनियम 1952 एवं कोयला खान विनियम 2017 के अंतर्गत वैधानिक योग्यता प्रणाली",
    
    // Admin Login
    adminLoginHeader: "वैधानिक नियामक प्रशासन",
    adminLoginSubheader: "झारखंड सरकार • खान एवं भूतत्व विभाग",
    adminRegulatoryNotice: "प्रतिबंधित आधिकारिक टर्मिनल। डीजीएमएस वैधानिक अनुपालन के तहत पहुंच की क्रिप्टोग्राफिक निगरानी की जाती है। हैकाथॉन मूल्यांकन हेतु नीचे प्राधिकृत पद चुनें।",
    adminRoleLabel: "प्राधिकार पद / उपयोगकर्ता नाम",
    adminRolePlaceholder: "अधिकारी का उपयोगकर्ता नाम दर्ज करें",
    adminPassLabel: "मास्टर प्राधिकार पासवर्ड",
    adminPassPlaceholder: "नियामक पासवर्ड दर्ज करें",
    captchaLabel: "सुरक्षा कैप्चा सत्यापन",
    captchaPlaceholder: "5-अक्षरों का कोड दर्ज करें",
    adminLoginBtn: "नियामक कंसोल में लॉगिन करें",
    adminLoggingIn: "पहचान प्रमाणित की जा रही है...",
    roleSafetyOfficerTitle: "साइट सुरक्षा अधिकारी",
    roleSafetyOfficerDesc: "बीसीसीएल / सीसीएल / ईसीएल खदानों में कामगार नामांकन एवं प्रशिक्षण निगरानी।",
    roleDgmsTitle: "डीजीएमएस निरीक्षक (धनबाद मुख्यालय)",
    roleDgmsDesc: "वैधानिक ऑडिट लेजर, SHA-256 HMAC क्रिप्टोग्राफिक प्रमाण पत्र सत्यापन।",
    roleStateTitle: "राज्य नोडल अधिकारी",
    roleStateDesc: "राज्यव्यापी खनन विश्लेषिकी, जिला स्तरीय अनुपालन एवं दुर्घटना रोकथाम सूचकांक।",
    adminDemoCredsNotice: "डेमो अधिकारी क्रेडेंशियल: उपयोगकर्ता नाम एवं पासवर्ड 'password123'",

    // Common Actions
    startSimulation: "एआर प्रशिक्षण शुरू करें",
    exitSimulation: "सिमुलेशन से बाहर निकलें",
    nextStep: "अगला चरण",
    previousStep: "पिछला",
    finishAssessment: "मूल्यांकन सबमिट करें",
    viewCertificate: "प्रमाण पत्र देखें",
    downloadCertificate: "क्यूआर प्रमाण पत्र डाउनलोड करें",
    printCertificate: "प्रमाण पत्र प्रिंट करें",
    savePdf: "पीडीएफ के रूप में सहेजें",
    returnToPortal: "पोर्टल पर वापस लौटें",
    certificateReadyTitle: "वैधानिक व्यावसायिक सुरक्षा प्रमाणपत्र तैयार",
    certificateReadySubtitle: "उच्च-रिज़ॉल्यूशन A4 प्रारूप • आधिकारिक खान सुरक्षा रिकॉर्ड",
    
    // Worker Portal - E-Identity Card
    workerProfileTitle: "कामगार ई-पहचान प्रोफाइल",
    activeMinerStatus: "वैधानिक सक्रिय खनिक",
    workforceCode: "कार्यबल कोड",
    sectorLabel: "खनन क्षेत्र",
    districtLabel: "जिला",
    activeCertsCounter: "सक्रिय डीजीएमएस प्रमाणपत्र",
    mandatoryDrillsCounter: "अनिवार्य सिमुलेशन",
    audioGuidanceBtn: "आवाज़ मार्गदर्शन",

    // Training Modules Section
    modulesSectionTitle: "वैधानिक व्यावसायिक एआर सुरक्षा मॉड्यूल",
    modulesSectionSubtitle: "खान सुरक्षा महानिदेशालय (DGMS) द्वारा निर्धारित व्यावहारिक कैमरा-आधारित सुरक्षा ड्रिल",
    certifiedBadge: "प्रमाणित",
    statutoryDrillBadge: "वैधानिक ड्रिल",
    phase2Badge: "द्वितीय चरण",
    underDgmsSpec: "डीजीएमएस विनिर्देश के तहत",
    passThresholdLabel: "उत्तीर्ण मानक:",
    
    // 5 Modules Details
    module1Title: "आग एवं विस्फोट प्रतिक्रिया",
    module1Subtitle: "निकास पहचान, अग्निशामक PASS तकनीक और आपातकालीन निकासी",
    module1Desc: "इंटरैक्टिव कैमरा एआर सिमुलेशन: आपातकालीन निकास मार्ग की पुष्टि, पिन खींचना, आग के आधार पर निशाना साधना, लीवर दबाना और सीएमआर 136 के तहत आग बुझाना।",
    module2Title: "गैस रिसाव एवं सीमित स्थान प्रोटोकॉल",
    module2Subtitle: "मीथेन (CH4), कार्बन मोनोऑक्साइड (CO), पीपीई और बडी संकेत",
    module2Desc: "कोयला खदान में वायुमंडलीय परीक्षण, मल्टी-गैस डिटेक्टर सीमा अंशांकन, धनात्मक-दबाव SCBA मास्क पहनना और वैधानिक 2-व्यक्ति बडी सिग्नलिंग।",
    module3Title: "मशीनरी एवं कन्वेयर सुरक्षा",
    module3Subtitle: "कन्वेयर बेल्ट लॉक-आउट टैग-आउट (LOTO), रोलर पिंच पॉइंट्स और आपातकालीन कॉर्ड",
    module3Desc: "वर्चुअल यांत्रिक रखरखाव ड्रिल: डीजीएमएस परिपत्र 2026 के अंतर्गत पावर आइसोलेशन पैडलॉकिंग, आपातकालीन ट्रिप वायर और कन्वेयर रोलर सुरक्षा जांच।",
    module4Title: "विद्युत एवं ब्लास्टिंग क्लीयरेंस",
    module4Subtitle: "फ्लेमप्रूफ एनक्लोजर निरीक्षण, विस्फोटक मैगजीन हैंडलिंग और ब्लास्टिंग घेरा",
    module4Desc: "खतरा निरीक्षण सिमुलेशन: एफएलपी इलेक्ट्रिकल स्विचगियर गैप गेज, डिटोनेटर परिवहन नियम और 300-मीटर ब्लास्टिंग शेल्टर निकासी का अनुपालन।",
    module5Title: "पीपीई अनुपालन एवं खदान प्रवेश",
    module5Subtitle: "अनिवार्य हेलमेट, स्टील-टो जूते, मेटाटार्सल गार्ड और धूल मास्क पहनना",
    module5Desc: "कंप्यूटर विज़न एवं एआर संरेखण जांच: कैप लैंप युक्त हेलमेट, परावर्तक सुरक्षा जैकेट, कान रक्षक और सुरक्षा जूते डीजीएमएस मानकों के अनुरूप सुनिश्चित करना।",
    
    // Passports / Certificates Section
    passportsSectionTitle: "सत्यापित व्यावसायिक सुरक्षा पासपोर्ट (सिमुलेशन रिकॉर्ड)",
    passportsSectionSubtitle: "खान अधिनियम 1952 एवं डीजीएमएस व्यावसायिक मानकों के तहत क्रिप्टोग्राफिक रूप से हस्ताक्षरित डिजिटल रिकॉर्ड।",
    certNumberLabel: "प्रमाणपत्र संख्या",
    statutoryValidityLabel: "वैधानिक वैधता:",
    noPassportsTitle: "अभी तक कोई पासपोर्ट जारी नहीं हुआ",
    noPassportsDesc: "ऊपर दिए गए व्यावहारिक एआर अग्निशामक अथवा मीथेन गैस ड्रिल को पूरा करें, डीजीएमएस सुरक्षा मूल्यांकन में ≥ 75% अंक प्राप्त करें, और आपका डिजिटल पासपोर्ट यहाँ स्वतः जुड़ जाएगा।",
    startDrillCta: "अभी एआर ड्रिल शुरू करें",

    // AR Fire PASS Steps
    fireHudTitle: "डीजीएमएस वैधानिक सिमुलेशन • सीएमआर विनियम 136 (PASS ड्रिल)",
    emergencyExitSign: "आपातकालीन शाफ्ट निकास मार्ग (25 मी) →",
    tapToLockAim: "नोजल निशाना लॉक करने के लिए आग के आधार पर टैप करें",
    passStep0Title: "चरण 0: आपातकालीन निकास मार्ग की पुष्टि",
    passStep0Desc: "अपने पीछे लगे हरे प्रकाश वाले निकास शाफ्ट संकेत को देखें। आगे बढ़ने से पहले सुनिश्चित करें कि पीछे हटने का रास्ता खुला है।",
    passStep0Btn: "निकास मार्ग सत्यापित: आगे बढ़ें →",
    passP_title: "चरण 1: सुरक्षा पिन खींचें (Pull)",
    passP_desc: "सील तोड़ें और हैंडल से सेफ्टी लॉकिंग पिन को बाहर खींचें।",
    passP_btn: "सुरक्षा लॉकिंग पिन खींचें →",
    passA_title: "चरण 2: आग के आधार पर निशाना लगाएं (Aim)",
    passA_desc: "नोजल को सीधे आग की जड़ (निचले हिस्से) पर केंद्रित करें, धुएं पर नहीं।",
    passA_btn: "ईंधन आधार पर निशाना लॉक हुआ →",
    passS1_title: "चरण 3: लीवर को दबाएं (Squeeze)",
    passS1_desc: "केमिकल झाग छोड़ने के लिए हैंडल लीवर को मजबूती से दबाएं।",
    passS1_btnHold: "झाग छोड़ने हेतु लीवर दबाए रखें",
    passS1_btnRelease: "लीवर छोड़ें",
    passS2_title: "चरण 4: अगल-बगल घुमाएं (Sweep)",
    passS2_desc: "आग पूरी तरह बुझने तक नोजल को दाएं-बाएं घुमाते रहें।",
    passS2_btn: "आग पर नोजल घुमाया जा रहा है...",
    fireCompleteTitle: "आग पूरी तरह बुझाई गई!",
    fireCompleteDesc: "आपने वैधानिक PASS तकनीक का सफल अभ्यास पूरा किया है। अब सुरक्षा निर्णय मूल्यांकन की ओर बढ़ें।",
    fireCompleteBtn: "योग्यता मूल्यांकन प्रारंभ करें →",

    // AR Gas Module Steps
    gasHudTitle: "वैधानिक मल्टी-गैस डिटेक्टर",
    gasDetectTitle: "चरण 1: वायुमंडलीय गैस निगरानी",
    gasDetectDesc: "गैस डिटेक्टर जांचें: मीथेन (< 1.25%), कार्बन मोनोऑक्साइड (< 50 ppm), ऑक्सीजन स्तर सामान्य (19.5% - 23.5%)।",
    gasDetectBtn: "कोयला खदान गैस रिसाव परीक्षण प्रारंभ करें →",
    gasAlarmTitle: "वैधानिक अलार्म: सीएमआर विनियम 142 का उल्लंघन",
    gasAlarmDesc: "मीथेन का स्तर वैधानिक विस्फोटक सीमा (1.25%) से अधिक हो गया है। बिना प्रमाणित SCBA ऑक्सीजन मास्क के आगे न बढ़ें।",
    gasAlarmBtn: "अलार्म स्वीकारें एवं SCBA मास्क पहनें →",
    gasPpeTitle: "चरण 2: अनिवार्य पीपीई पहनना",
    gasPpeDesc: "ऑक्सीजन मास्क (SCBA), कैप लैंप युक्त हेलमेट और हार्नेस रस्सी पहनें।",
    gasPpeBtn: "पीपीई एवं ऑक्सीजन सिलेंडर सील की पुष्टि करें →",
    gasBuddyTitle: "चरण 3: 2-व्यक्ति बडी सिग्नल",
    gasBuddyDesc: "सीमित खदान सुरंग में प्रवेश से पूर्व बाहर खड़े साथी के साथ रेडियो संपर्क जांचें।",
    gasBuddyBtn: "साथी के साथ 2-तरफा रेडियो संपर्क की पुष्टि करें →",
    gasCompleteTitle: "गैस खतरा नियंत्रित एवं सुरक्षित निकासी",
    gasCompleteDesc: "डीजीएमएस दिशानिर्देशों के तहत सभी वायुमंडलीय मानक एवं बडी प्रोटोकॉल सफलतापूर्वक पूरे किए गए।",
    gasCompleteBtn: "योग्यता मूल्यांकन प्रारंभ करें →",
    sensorOk: "सामान्य",
    sensorCritical: "खतरनाक",
    sensorToxic: "विषाक्त",
    sensorDeficient: "ऑक्सीजन कम",

    // Scenario Quiz
    quizHeader: "डीजीएमएस वैधानिक निर्णय मूल्यांकन",
    questionCounter: "प्रश्न",
    ofLabel: "का",
    complianceBenchmarkNotice: "खान सुरक्षा अनुपालन मानक: 75%",
    selectAnswerPrompt: "आगे बढ़ने के लिए कृपया कोई एक उत्तर चुनें",
    submitDecisionBtn: "निर्णय सबमिट करें",
    nextQuestionBtn: "अगला प्रश्न →",
    quizPassedTitle: "डीजीएमएस वैधानिक मूल्यांकन: उत्तीर्ण (PASSED)",
    quizFailedTitle: "योग्यता मानक पूर्ण नहीं हुआ",
    quizPassedDesc: "उम्मीदवार ने खान अधिनियम 1952 के तहत वैधानिक सुरक्षा निर्णय मानकों को पूर्ण किया है। क्रिप्टोग्राफिक क्यूआर प्रमाणपत्र तैयार किया जा रहा है।",
    quizFailedDesc: "उम्मीदवार का स्कोर अनिवार्य 75% डीजीएमएस उत्तीर्ण मानक से कम है। कृपया सुरक्षा निर्देशों की समीक्षा करें और पुनः सिमुलेशन अभ्यास करें।",
    scoreAccuracyLabel: "निर्णय सटीकता",
    scoreTechniqueLabel: "एआर तकनीक अंक",
    scoreEvaluationLabel: "अंतिम मूल्यांकन",
    verifiedForIssuance: "✓ वैधानिक प्रमाणपत्र जारी करने हेतु सत्यापित",
    retakeDrillBtn: "पुनः सिमुलेशन अभ्यास करें",
    generateCertBtn: "प्रमाणपत्र बनाएं एवं देखें",
    voiceCorrect: "सटीक वैधानिक निर्णय!",
    voiceIncorrect: "अनुचित निर्णय। डीजीएमएस वैधानिक व्याख्या की समीक्षा करें।",

    // Safety Officer Dashboard
    officerDashboardTitle: "साइट सुरक्षा अधिकारी कार्यबल रोस्टर",
    officerSiteSubtitle: "जनजातीय भाषा वरीयता, साक्षरता संकेतक एवं सक्रिय वैधानिक सुरक्षा प्रमाणन की निगरानी",
    enrolWorkerBtn: "नए फ्रंटलाइन कामगार का नामांकन करें",
    kpiTotalMiners: "पंजीकृत कुल कार्यबल",
    kpiCertifiedRate: "वैधानिक अनुपालन दर",
    kpiPendingDrills: "प्रशिक्षण शेष खनिक",
    kpiTribalWorkforce: "जनजातीय भाषा प्रयोक्ता",
    searchPlaceholder: "कामगार का नाम अथवा आईडी खोजें...",
    filterAllCohorts: "सभी प्रशिक्षण समूह (Cohorts)",
    thWorkerId: "कामगार कोड",
    thNameDesig: "नाम एवं पद",
    thSite: "खदान / संयंत्र स्थल",
    thLanguage: "जनजातीय भाषा",
    thStatus: "सुरक्षा स्थिति",
    thCerts: "प्रमाणपत्र",
    thActions: "कार्रवाई",
    enrolModalTitle: "नए फ्रंटलाइन कामगार का नामांकन",
    enrolModalDesc: "डीजीएमएस व्यावसायिक प्रशिक्षण मानकों एवं भाषा वरीयता के साथ खनिक को पंजीकृत करें।",
    fieldName: "पूरा नाम",
    fieldNamePlaceholder: "उदा. बिरसा हांसदा",
    fieldLanguage: "प्राथमिक भाषा",
    fieldDesignation: "कार्यबल पद",
    fieldDesignationPlaceholder: "उदा. भूमिगत ड्रिलर",
    fieldMobile: "पंजीकृत मोबाइल नंबर",
    fieldCohort: "प्रशिक्षण समूह (Cohort)",
    submitEnrolBtn: "कामगार पंजीकृत करें",
    cancelBtn: "रद्द करें",

    // DGMS Inspector Portal
    dgmsHeaderTitle: "खान सुरक्षा महानिदेशालय (DGMS)",
    dgmsHeaderSubtitle: "वैधानिक ऑडिट एवं सत्यापन टर्मिनल • धनबाद मुख्यालय",
    searchLedgerTitle: "क्रिप्टोग्राफिक प्रमाणपत्र सत्यापन टर्मिनल",
    searchLedgerDesc: "आधिकारिक राज्य लेजर रिकॉर्ड की जांच हेतु SHA-256 HMAC हैश अथवा प्रमाणपत्र संख्या दर्ज करें:",
    searchHashPlaceholder: "SHA-256 हैश अथवा प्रमाणपत्र कोड दर्ज करें (उदा. CERT-JH-2026-10000)",
    verifyBtn: "सत्यापन जांचें",
    kpiAuditedMines: "ऑडिट किए गए खदान स्थल",
    kpiCryptoPassports: "डिजिटल सुरक्षा पासपोर्ट",
    kpiLedgerIntegrity: "लेजर अखंडता जांच",
    kpiIntegrityStatus: "100% SHA-256 प्रामाणिक",
    kpiViolations: "उल्लंघन दर्ज",
    thCertId: "प्रमाणपत्र संख्या",
    thWorker: "कामगार कोड एवं नाम",
    thModule: "सुरक्षा मॉड्यूल",
    thScore: "अंक",
    thIssueDate: "जारी तिथि",
    thLedgerHash: "लेजर हैश (HMAC-SHA256)",
    thAuditStatus: "वैधानिक स्थिति",
    btnInspect: "रिकॉर्ड जांचें",
    modalAuditTitle: "डीजीएमएस वैधानिक लेजर निरीक्षण",
    modalAuditDesc: "धनबाद केंद्रीय सर्वर के विरुद्ध क्रिप्टोग्राफिक प्रमाण एवं कामगार अनुपालन अखंडता सत्यापित।",
    tamperProofValid: "अपरिवर्तनीय डिजिटल हस्ताक्षर सत्यापित",
    btnClose: "बंद करें",

    // State Nodal Dashboard
    stateHeaderTitle: "खान एवं भूतत्व विभाग • झारखंड सरकार",
    stateHeaderSubtitle: "राज्यव्यापी खनन व्यावसायिक सुरक्षा एवं एआर प्रशिक्षण विश्लेषिकी",
    kpiTotalWorkforce: "कुल पंजीकृत कार्यबल",
    kpiStateCompliance: "राज्यव्यापी अनुपालन दर",
    kpiDrillsCompleted: "पूर्ण एआर सुरक्षा सिमुलेशन",
    kpiIncidentIndex: "सुरक्षा एवं दुर्घटना रोकथाम सूचकांक",
    chartDistrictTitle: "जिला-वार अनुपालन मानक",
    chartLanguageTitle: "एआर प्रशिक्षण में जनजातीय भाषा वितरण",
    chartModuleTitle: "मॉड्यूल-वार योग्यता दक्षता",
    thDistrict: "जिला",
    thSector: "प्रमुख खनिज क्षेत्र",
    thMinesCount: "सक्रिय खदानें / संयंत्र",
    thEnrolledMiners: "पंजीकृत खनिक",
    thDistrictRate: "अनुपालन दर",
    thDistrictStatus: "वैधानिक स्थिति",
    exportReportBtn: "विस्तृत राज्य रिपोर्ट डाउनलोड करें (CSV / PDF)",

    // Global Footer
    footerLinkHome: "मुखपृष्ठ",
    footerLinkSimulator: "सिम्युलेटर जानकारी",
    footerLinkCurriculum: "पाठ्यक्रम मॉडल",
    footerLinkRti: "आरटीआई प्रकटीकरण",
    footerLinkEvaluation: "मूल्यांकन दल",
    footerLinkActs: "अधिनियम एवं नियम",
    footerLinkSafety: "सुरक्षा ढांचा",
    footerLinkScreenReader: "स्क्रीन रीडर पहुंच",
    footerLinkOfficialLogin: "विभागीय लॉगिन",
    footerDeptTitle: "झारखंड सरकार • खान एवं भूतत्व विभाग",
    footerDeptDesc: "डीजीएमएस व्यावसायिक दिशानिर्देशों के तहत जनजातीय एवं खनिज कामगारों के सशक्तिकरण हेतु निर्मित सहयोगी सुरक्षा सिम्युलेटर।",
    footerDgmsTitle: "वैधानिक नियामक मानक",
    footerDgmsDesc: "खान अधिनियम 1952, कोयला खान विनियम 2017 एवं शून्य दुर्घटना लक्ष्य हेतु डीजीएमएस परिपत्रों के अनुरूप।",
    footerSihTitle: "स्मार्ट इंडिया हैकाथॉन 2026 शैक्षणिक सुरक्षित बंदरगाह",
    footerSihDesc: "प्रॉब्लम स्टेटमेंट 26041 हेतु तकनीकी प्रोटोटाइप। उत्पन्न सभी डेटा एवं प्रमाणपत्र शैक्षणिक मूल्यांकन हेतु हैं।",
    footerCopyright: "© 2026 झारखंड सरकार एवं खान सुरक्षा महानिदेशालय (DGMS)। स्मार्ट इंडिया हैकाथॉन 2026 हेतु तकनीकी प्रोटोटाइप।",

    // Audio Prompts
    audioPullPin: "अग्निशामक यंत्र की सेफ्टी पिन खींचें।",
    audioAimBase: "नोजल को आग के निचले हिस्से पर रखें।",
    audioSqueezeLever: "हैंडल को दबाकर झाग छोड़ें।",
    audioSweepFire: "नोजल को दाएं-बाएं घुमाएं।",
    audioGasAlarm: "खतरा! जहरीली गैस का स्तर बढ़ा। तुरंत ऑक्सीजन मास्क पहनें!",
    audioBuddyConfirm: "सुरंग में जाने से पहले साथी को रेडियो संकेत दें।",

    // Additional Gas Module keys
    gasHudAuditNotice: "डीजीएमएस वैधानिक सेंसर: वायुमंडलीय गैस ऑडिट",
    gasAlarmNotice: "डीजीएमएस खतरा: सीमित गैस सीमा पार (सीएमआर 142)",
    gasHeadingLabel: "डीजीएमएस सीमित कोयला सीम हेडिंग #3 • वायुमंडलीय गैस सेंसर सक्रिय",
    gasMethaneLimit: "मीथेन CH₄ (डीजीएमएस <1.25%):",
    gasCoLimit: "सीओ (डीजीएमएस <50ppm):",
    gasOxygenLimit: "ऑक्सीजन O₂ (डीजीएमएस 19.5-21%):",
    gasPpeVerifyPrompt: "खान अधिनियम 1952 के तहत प्रत्येक अनिवार्य सुरक्षा उपकरण की पुष्टि करें:",
    gasPpeMask: "1. पॉजिटिव-प्रेशर SCBA ऑक्सीजन मास्क",
    gasPpeFitMask: "[मास्क पहनने के लिए टैप करें]",
    gasPpeHelmet: "2. एंटीस्टैटिक हेलमेट (एलईडी लैंप सहित)",
    gasPpeLockHelmet: "[हेलमेट लॉक करने के लिए टैप करें]",
    gasPpeHarness: "3. फुल-बॉडी सेफ्टी हार्नेस एवं लाइफलाइन",
    gasPpeAttachLifeline: "[लाइफलाइन जोड़ने के लिए टैप करें]",
    gasPpeProceedBtn: "पीपीई सत्यापित • बडी संचार जांच के लिए आगे बढ़ें →",
    gasPpeRequiredPrompt: "आगे बढ़ने के लिए तीनों अनिवार्य उपकरण पहनें",
    gasBuddyReqPrompt: "खान अधिनियम धारा 22 के अनुसार सतह पर तैनात साथी से संचार सत्यापन आवश्यक है:",
    gasBuddyRadio: "रेडियो संचार फ्रीक्वेंसी जांच (चैनल 4 माइनिंग बैंड)",
    gasBuddyCheckRadio: "[सिग्नल जांचें]",
    gasBuddyLifeline: "लाइफलाइन टग प्रोटोकॉल (2 झटके = सामान्य, 3 झटके = आपातकाल)",
    gasBuddyConfirmLifeline: "[टग की पुष्टि करें]",
    gasBuddyRequiredPrompt: "जारी रखने के लिए बडी प्रोटोकॉल पूरा करें",
    gasProtocolSuccessVoice: "प्रोटोकॉल सत्यापित। सीमित स्थान में प्रवेश स्वीकृत।",

    // Additional Scenario Quiz keys
    quizAssessmentTitle: "डीजीएमएस वैधानिक योग्यता मूल्यांकन",
    quizPaperSub: "खान अधिनियम 1952 • परीक्षा पत्र",
    quizCorrectDecision: "सही नियामक निर्णय",
    quizViolation: "डीजीएमएस सुरक्षा उल्लंघन",
    quizViewResultsBtn: "मूल्यांकन परिणाम देखें →",
    quizNextBtn: "अगला प्रश्न →",
    quizSubmitBtn: "उत्तर सबमिट करें एवं निर्णय सत्यापित करें →",

    // Certificate Top Bar keys
    certActionBarTitle: "वैधानिक व्यावसायिक सुरक्षा प्रमाणपत्र तैयार है",
    certA4Format: "उच्च-रिज़ॉल्यूशन A4 प्रारूप",
    certOfficialRecord: "आधिकारिक खान सुरक्षा रिकॉर्ड",
    saveAsPdf: "पीडीएफ के रूप में सहेजें",

    // Safety Officer Dashboard keys
    officerStationTitle: "वैधानिक पर्यवेक्षी स्टेशन",
    officerDistrict: "जिला",
    officerSector: "क्षेत्र",
    officerSupervisoryOfficer: "पर्यवेक्षी अधिकारी",
    officerStationSub: "डीजीएमएस वैधानिक प्रशिक्षण स्टेशन #4",
    officerOnboardRecruit: "नए कामगार को नामांकित करें",
    officerCohortBatch: "प्रशिक्षण समूह बैच",
    officerEnrolledMiners: "नामांकित",
    officerMinersLabel: "कामगार",
    officerCertifiedMiners: "प्रमाणित",
    officerRosterTitle: "अग्रिम पंक्ति कामगार रोस्टर एवं डीजीएमएस प्रमाणन स्थिति",
    officerRosterSubtitle: "जनजातीय भाषा प्राथमिकता, साक्षरता संकेतक और सक्रिय वैधानिक सुरक्षा प्रमाणन की निगरानी",
    officerSearchPlaceholder: "कामगार का नाम या आईडी खोजें...",
    officerAllCohorts: "सभी प्रशिक्षण बैच",
    officerThWorkerCode: "कामगार कोड",
    officerThFullName: "पूरा नाम",
    officerThTribalLang: "जनजातीय भाषा",
    officerThLiteracy: "साक्षरता",
    officerThDesignation: "पद",
    officerThActiveCerts: "सक्रिय प्रमाणपत्र",
    officerThStatus: "वैधानिक स्थिति",
    officerCompliantBadge: "डीजीएमएस अनुपालित",
    officerTrainingDueBadge: "प्रशिक्षण शेष",
    officerDrillsCount: "ड्रिल",
    officerBestScore: "सर्वश्रेष्ठ",
    officerModalTitle: "नए जनजातीय कामगार को नामांकित करें",
    officerModalSubtitle: "कैमरा-आधारित एआर प्रशिक्षण हेतु कामगार को पंजीकृत करें।",
    officerFieldFullName: "पूरा नाम (जनजातीय उपनाम सहित):",
    officerFieldPrimaryLang: "प्राथमिक भाषा:",
    officerFieldDesignation: "पद:",
    officerFieldContact: "संपर्क फोन नंबर:",
    officerFieldAssignCohort: "प्रशिक्षण बैच में आवंटित करें:",
    officerBtnCancel: "रद्द करें",
    officerBtnSubmitEnroll: "कामगार का नामांकन करें एवं एआर मॉड्यूल सौंपें",

    // DGMS Portal keys
    dgmsConsoleBadge: "नियामक सिमुलेशन कंसोल",
    dgmsBenchmarkSub: "डीजीएमएस मानक बेंचमार्क कंसोल • धनबाद नियामक ढांचा",
    dgmsLedgerTitle: "खान अधिनियम 1952 अनुपालन लेज़र (डीजीएमएस नियामक सिमुलेशन)",
    dgmsAuditorLabel: "सिम्युलेटेड ऑडिटर / निरीक्षक",
    dgmsBenchmarkRef: "नियामक संदर्भ: DGMS/S&T/Circular-2026/041",
    dgmsExportCsv: "वैधानिक ऑडिट लॉग निर्यात करें (CSV)",
    dgmsScannerTitle: "लाइव ऑन-साइट क्यूआर प्रमाणपत्र सत्यापनकर्ता एवं जालसाजी-रोधी स्कैनर",
    dgmsScannerDesc: "वास्तविक समय में लेज़र प्रामाणिकता सत्यापित करने के लिए कामगार कार्ड क्यूआर स्कैन करें या प्रमाणपत्र आईडी / हैश दर्ज करें",
    dgmsInputPlaceholder: "क्यूआर हैश या प्रमाणपत्र आईडी दर्ज करें...",
    dgmsVerifying: "डीजीएमएस लेज़र की जांच जारी...",
    dgmsVerifyBtn: "प्रामाणिकता सत्यापित करें →",
    dgmsTestValid: "वैध प्रमाणपत्र जांचें",
    dgmsTestForgery: "फर्जी प्रमाणपत्र जांचें",
    dgmsVerifiedAuthentic: "सत्यापित प्रामाणिक: डीजीएमएस वैधानिक रूप से अनुपालित",
    dgmsFraudDetected: "रिकॉर्ड नहीं मिला अथवा धोखाधड़ी/जालसाजी पाई गई",
    dgmsVerifiedDetail: "राज्य लेज़र के विरुद्ध क्रिप्टोग्राफ़िक SHA-256 HMAC डिजिटल हस्ताक्षर मान्य। शून्य डेटा छेड़छाड़ मिली।",
    dgmsFraudDetail: "प्रस्तुत क्यूआर हैश रिकॉर्ड से मेल नहीं खाता है या इसमें छेड़छाड़ की गई है।",
    dgmsWorkerDetails: "कामगार विवरण",
    dgmsMineFacility: "खान सुविधा स्थल",
    dgmsModuleCompetency: "मॉड्यूल योग्यता",
    dgmsValidityWindow: "वैधानिक वैधता अवधि",
    dgmsPassedTag: "अंक: {score}% (उत्तीर्ण)",
    dgmsExpiresLabel: "समाप्ति तिथि",
    dgmsRefresherDays: "दिन अनिवार्य पुनश्चर्या प्रशिक्षण हेतु शेष",
    dgmsViewPrintCert: "प्रमाणपत्र देखें एवं प्रिंट करें",
    dgmsAuditRegisterTitle: "खान अधिनियम, 1952 वैधानिक ऑडिट रजिस्टर",
    dgmsAuditRegisterDesc: "क्रिप्टोग्राफिक हैश के साथ जारी सभी योग्यता प्रमाणपत्रों का अनिवार्य डिजिटल रजिस्टर",
    dgmsFilterSector: "क्षेत्र के अनुसार फ़िल्टर करें:",
    dgmsSectorAll: "सभी औद्योगिक क्षेत्र",
    dgmsSectorCoal: "कोयला खनन (BCCL / CCL)",
    dgmsSectorSteel: "इस्पात प्रसंस्करण (SAIL / Tata)",
    dgmsSectorMica: "अभ्रक संवर्धन (कोडरमा / गिरिडीह)",
    dgmsThCertId: "प्रमाणपत्र आईडी",
    dgmsThWorkerCode: "कामगार कोड",
    dgmsThWorkerName: "कामगार नाम",
    dgmsThMineSite: "खान / संयंत्र स्थल",
    dgmsThDistrict: "जिला",
    dgmsThScore: "अंक",
    dgmsThIssueDate: "जारी तिथि",
    dgmsThExpiryDate: "समाप्ति तिथि",
    dgmsThStatus: "वैधानिक स्थिति",
    dgmsThVerify: "सत्यापन",
    dgmsBtnAudit: "ऑडिट",
    dgmsBtnPrint: "प्रिंट",
    dgmsClosePreview: "✕ निरीक्षक पूर्वावलोकन बंद करें",

    // State Nodal Dashboard keys
    stateConsoleBadge: "राज्य नोडल विश्लेषिकी",
    stateConsoleSub: "शैक्षणिक सिमुलेशन कंसोल • खान एवं भूतत्व विभाग (झारखंड सरकार) पर आधारित",
    stateMainTitle: "झारखंड औद्योगिक खान सुरक्षा — राज्य विश्लेषिकी एवं अनुपालन सिमुलेशन",
    stateOfficerLine: "सिम्युलेटेड राज्य नोडल अधिकारी",
    stateSandboxNotice: "तकनीकी मूल्यांकन सैंडबॉक्स • वास्तविक समय नियामक मेट्रिक्स",
    stateFrameworkTag: "वैधानिक ढांचा: खान अधिनियम 1952 (डीजीएमएस परिपत्र)",
    stateKpiCertified: "कुल प्रमाणित कामगार",
    stateKpiGrowth: "↑ 18.4% माह-दर-माह वृद्धि",
    stateKpiPassRate: "कुल उत्तीर्ण दर",
    stateKpiDgmsBenchmark: "डीजीएमएस मानक: 75%",
    stateKpiActiveSites: "सक्रिय खनन स्थल",
    stateKpiUnits: "कोयला, इस्पात एवं अभ्रक इकाइयाँ",
    stateKpiRefresherDue: "पुनश्चर्या शेष (<30 दिन)",
    stateKpiNoticeIssued: "साइट अधिकारियों को नोटिस जारी",
    stateChart1Title: "जिलावार साप्ताहिक प्रमाणन मात्रा",
    stateChart1Sub: "धनबाद, बोकारो, रामगढ़ एवं कोडरमा में प्रशिक्षण प्रगति",
    stateChart2Title: "एआर प्रशिक्षण में जनजातीय भाषा वितरण",
    stateChart2Sub: "कामगारों द्वारा वॉयसओवर और लिपि के उपयोग का विवरण",
    stateRadarTitle: "वैधानिक 30-दिवसीय प्रमाणपत्र समाप्ति चेतावनी रडार",
    stateRadarSub: "खान अधिनियम 1952 वार्षिक पुनश्चर्या अनिवार्य करता है। 30 दिनों में समाप्त होने वाले कामगार नीचे सूचीबद्ध हैं।",
    stateActionRequired: "साइट पर्यवेक्षकों द्वारा कार्रवाई आवश्यक",
    stateThCertId: "प्रमाणपत्र आईडी",
    stateThWorkerCode: "कामगार कोड",
    stateThWorkerName: "कामगार नाम",
    stateThContactPhone: "संपर्क फोन",
    stateThMineSite: "खान स्थल",
    stateThIssueDate: "जारी तिथि",
    stateThExpiryDate: "वैधानिक समाप्ति",
    stateThStatus: "स्थिति",
    stateRefresherDueBadge: "⚠ पुनश्चर्या शेष",
    stateAllCompliant: "सभी वैधानिक प्रमाणपत्र वर्तमान में वैध अनुपालन अवधि में हैं।",

    // Extended Footer keys
    footerDeptTitleText: "स्मार्ट इंडिया हैकाथॉन 2026 (PS ID: 26041)",
    footerDeptSubText: "एआर व्यावसायिक खनन सुरक्षा सिमुलेशन इंजन",
    footerDeptBodyText: "स्मार्ट इंडिया हैकाथॉन 2026 के लिए विकसित शैक्षणिक तकनीकी प्रोटोटाइप। खान एवं भूतत्व विभाग (झारखंड सरकार) के पाठ्यक्रम और खान अधिनियम 1952 तथा डीजीएमएस मानकों पर आधारित।",
    footerStandardsTitleText: "मानक एवं दिशानिर्देश",
    footerStd1Text: "• खान सुरक्षा महानिदेशालय (DGMS) सुरक्षा मानदंड",
    footerStd2Text: "• खान अधिनियम, 1952 एवं कारखाना अधिनियम, 1948 योग्यता मानक",
    footerStd3Text: "• स्मार्ट इंडिया हैकाथॉन 2026 — समस्या विवरण आईडी: 26041",
    footerStd4Text: "• भारतीय सरकारी वेबसाइटों के दिशानिर्देश (GIGW 3.0 / WCAG 2.1 AA)",
    footerDevTitleText: "विकास एवं सेफ हार्बर संदर्भ",
    footerDevByText: "SIH 2026 टीम द्वारा विकसित (समस्या विवरण आईडी: 26041)",
    footerDevSubText: "खनन एवं इस्पात सुरक्षा प्रशिक्षण हेतु शैक्षणिक एवं अनुसंधान प्रोटोटाइप",
    footerDrillCountText: "सिम्युलेटेड कामगार ड्रिल गणना:",
    footerLegalDisclaimerText: "कानूनी अस्वीकरण एवं उचित व्यवहार सूचना: यह मंच स्मार्ट इंडिया हैकाथॉन 2026 (समस्या विवरण आईडी: 26041) के लिए बनाया गया एक स्वतंत्र शैक्षणिक और तकनीकी सिमुलेशन प्रोटोटाइप है। यह आधिकारिक सरकारी पोर्टल नहीं है और झारखंड सरकार, डीजीएमएस या एनआईसी से औपचारिक रूप से संबद्ध नहीं है।",
    footerCopyrightNoticeText: "सभी वैधानिक नाम, प्रतीक और नियामक मानक भारतीय कॉपीराइट अधिनियम, 1957 की धारा 52 के तहत केवल प्रतियोगिता मूल्यांकन और शैक्षणिक प्रदर्शन के लिए संदर्भित हैं।"
  },

  sat: {
    // App & Branding
    appTitle: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ AR ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ",
    appSubtitle: "DGMS ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱵᱮᱵᱚᱥᱛᱟ",
    portalWorker: "ᱠᱟᱹᱢᱤᱭᱟᱹ AR ᱥᱮᱪᱮᱫ",
    portalOfficer: "ᱥᱟᱭᱤᱴ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱚᱯᱷᱤᱥᱚᱨ",
    portalDGMS: "DGMS ᱫᱷᱟᱱᱵᱟᱫᱽ ᱯᱚᱨᱠᱷᱟᱣ",
    portalState: "ᱯᱚᱱᱚᱛ ᱱᱚᱰᱟᱞ ᱰᱮᱥᱵᱚᱨᱰ",
    sihTitle: "ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ • PS ID: ᱒᱖᱐᱔᱑",
    sihAcademicBadge: "ᱥᱮᱪᱮᱫ ᱱᱚᱢᱩᱱᱟ",
    sihDisclaimer: "ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ (PS ID: ᱒᱖᱐᱔᱑) — ᱴᱮᱠᱱᱤᱠᱟᱞ ᱥᱮᱪᱮᱫ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱤᱢᱩᱞᱮᱴᱚᱨ᱾ ᱱᱚᱶᱟ ᱫᱚ ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ ᱟᱨᱵᱟᱝ DGMS ᱨᱮᱱᱟᱜ ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱯᱚᱨᱴᱟᱞ ᱫᱚ ᱵᱟᱝ ᱠᱟᱱᱟ᱾ ᱥᱮᱪᱮᱫ ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱱᱟᱣ ᱟᱠᱟᱱᱟ᱾",
    skipToContent: "ᱢᱩᱬᱩᱛ ᱥᱟᱛᱟᱢ ᱛᱮ ᱥᱮᱱᱚᱜ ᱢᱮ",
    screenReader: "ᱥᱠᱨᱤᱱ ᱯᱟᱲᱦᱟᱣᱤᱡ",
    sihHelpdesk: "SIH ᱜᱚᱲᱚ: PS-26041",
    
    // Status & Utility Controls
    online: "ᱚᱱᱞᱟᱭᱤᱱ ᱠᱞᱟᱣᱩᱰ ᱡᱚᱲᱟᱣ",
    offline: "ᱚᱯᱷᱞᱟᱭᱤᱱ ᱡᱟᱭᱜᱟ ᱨᱮ ᱥᱟᱧᱪᱟᱣ",
    voiceNarration: "ᱨᱚᱲ ᱛᱮ ᱞᱟᱹᱭ",
    soundOn: "ᱟᱲᱟᱝ ᱪᱟᱹᱞᱩ",
    soundOff: "ᱟᱲᱟᱝ ᱵᱚᱸᱫᱽ",
    speaking: "ᱨᱚᱲ ᱠᱟᱱᱟ...",
    cloudSynced: "ᱠᱞᱟᱣᱩᱰ ᱡᱚᱲᱟᱣ",
    offlineCount: "ᱚᱯᱷᱞᱟᱭᱤᱱ",
    syncNow: "ᱥᱤᱸᱠ",
    syncing: "ᱥᱤᱸᱠ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
    selectLanguage: "ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ",
    activeMinerBadge: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱷᱟᱫᱟᱱ ᱦᱚᱲ",
    activeAdminBadge: "ᱟᱹᱭᱫᱟᱹᱨᱤ ᱟᱱ ᱚᱯᱷᱤᱥᱚᱨ",
    logOut: "ᱚᱰᱚᱠᱚᱜ",
    workerWorkspace: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱟᱹᱢᱤ ᱴᱷᱟᱶ",
    adminWorkspace: "ᱥᱚᱨᱠᱟᱨᱤ ᱠᱚᱱᱥᱳᱞ",
    
    // Navigation Tabs
    tabModules: "AR ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ",
    tabCertificates: "ᱥᱟᱹᱠᱷᱤ ᱥᱟᱠᱟᱢ (QR)",
    tabProfile: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱩᱯᱨᱩᱢ",
    tabOfficer: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱚᱯᱷᱤᱥᱚᱨ",
    tabDgms: "DGMS ᱪᱮᱠ ᱞᱮᱡᱚᱨ",
    tabState: "ᱯᱚᱱᱚᱛ ᱞᱮᱠᱷᱟ",

    // Offline Banner
    offlineNoticeTitle: "ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱵᱟᱰᱟᱭ:",
    offlineNoticeDesc: "ᱯᱚᱨᱴᱟᱞ ᱫᱚ ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱳᱰ ᱨᱮ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜ-ᱟ᱾ ᱥᱮᱪᱮᱫ ᱢᱚᱰᱩᱞ ᱟᱨ ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱞᱳᱠᱟᱞ IndexedDB ᱨᱮ ᱥᱟᱧᱪᱟᱣ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    syncPendingTitle: "ᱯᱚᱱᱚᱛ ᱞᱮᱡᱚᱨ ᱥᱤᱸᱠ:",
    syncPendingDesc: "ᱥᱮᱪᱮᱫ ᱨᱮᱠᱳᱨᱰ ᱥᱚᱨᱠᱟᱨᱤ ᱞᱮᱡᱚᱨ ᱛᱮ ᱵᱷᱮᱡᱟᱭ ᱞᱟᱹᱜᱤᱫ ᱛᱟᱺᱜᱤ ᱨᱮ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    syncSuccessTitle: "ᱞᱮᱡᱚᱨ ᱥᱤᱸᱠ ᱮᱱᱟ:",
    syncSuccessDesc: "ᱥᱮᱪᱮᱫ ᱨᱮᱠᱳᱨᱰ ᱯᱚᱱᱚᱛ ᱞᱮᱡᱚᱨ ᱨᱮ ᱥᱟᱹᱨᱤ ᱛᱮ ᱫᱚᱦᱚ ᱮᱱᱟ᱾",
    
    // Worker Login
    workerLoginHeader: "ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ ᱯᱚᱨᱴᱟᱞ",
    workerLoginSubheader: "ᱠᱟᱹᱢᱤᱭᱟᱹ AR ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ ᱯᱚᱨᱴᱟᱞ",
    workerLoginGuidanceTitle: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱞᱟᱹᱜᱤᱫ ᱫᱤᱥᱟᱹ:",
    workerLoginGuidanceText: "ᱱᱚᱶᱟ ᱯᱚᱨᱴᱟᱞ ᱫᱚ ᱠᱷᱟᱫᱟᱱ ᱟᱨ ᱠᱟᱹᱨᱜᱟᱲ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱮ.ᱟᱨ (AR) ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ ᱟᱨ DGMS ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱮᱢᱚᱜ-ᱟ᱾",
    workforceIdLabel: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ / ᱢᱳᱵᱟᱭᱤᱞ ᱱᱚᱢᱵᱚᱨ",
    workforceIdPlaceholder: "ᱡᱮᱞᱮᱠᱟ: JH-WRK-001 ᱟᱨᱵᱟᱝ ᱢᱳᱵᱟᱭᱤᱞ",
    workerPinLabel: "᱔-ᱱᱚᱢᱵᱚᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ PIN ᱮᱢ ᱢᱮ",
    workerPinHelp: "ᱰᱮᱢᱳ PIN ᱫᱚ 1234 ᱠᱟᱱᱟ",
    loginSubmitBtn: "PIN ᱯᱚᱨᱠᱷᱟᱣ ᱠᱟᱛᱮ ᱵᱚᱞᱚᱱ ᱢᱮ",
    loginSubmitting: "ᱯᱚᱨᱠᱷᱟᱣ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
    demoMinersTitle: "ᱰᱮᱢᱳ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱵᱟᱪᱷᱟᱣ ᱢᱮ:",
    demoMinersDesc: "ᱦᱮᱠᱟᱛᱷᱚᱱ ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱡᱟᱦᱟᱸᱭ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱨᱮ ᱠᱞᱤᱠ ᱠᱟᱛᱮ ᱵᱚᱞᱚᱱ ᱢᱮ:",
    statutoryComplianceNotice: "Mines Act 1952 ᱟᱨ Coal Mines Regulations 2017 ᱞᱮᱠᱟᱛᱮ ᱥᱮᱪᱮᱫ",
    
    // Admin Login
    adminLoginHeader: "ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱱ ᱪᱟᱪᱞᱟᱣ",
    adminLoginSubheader: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ • ᱠᱷᱟᱫᱟᱱ ᱟᱨ ᱵᱷᱩᱛᱚᱛᱣᱚ ᱵᱤᱵᱷᱟᱜᱽ",
    adminRegulatoryNotice: "ᱚᱯᱷᱤᱥᱚᱨ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱴᱷᱟᱶ᱾ DGMS ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱡᱚᱛᱚ ᱠᱟᱹᱢᱤ ᱨᱮᱠᱳᱨᱰᱚᱜ ᱠᱟᱱᱟ᱾ ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱞᱟᱛᱟᱨ ᱨᱮ ᱯᱚᱫᱽ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾",
    adminRoleLabel: "ᱚᱯᱷᱤᱥᱚᱨ ᱯᱚᱫᱽ / ᱤᱭᱩᱡᱚᱨ ᱧᱩᱛᱩᱢ",
    adminRolePlaceholder: "ᱤᱭᱩᱡᱚᱨ ᱧᱩᱛᱩᱢ ᱮᱢ ᱢᱮ",
    adminPassLabel: "ᱢᱩᱬᱩᱛ ᱯᱟᱥᱣᱟᱨᱰ",
    adminPassPlaceholder: "ᱯᱟᱥᱣᱟᱨᱰ ᱮᱢ ᱢᱮ",
    captchaLabel: "ᱨᱩᱠᱷᱤᱭᱟᱹ CAPTCHA ᱯᱚᱨᱠᱷᱟᱣ",
    captchaPlaceholder: "᱕-ᱪᱤᱠᱤ ᱠᱳᱰ ᱮᱢ ᱢᱮ",
    adminLoginBtn: "ᱠᱚᱱᱥᱳᱞ ᱨᱮ ᱵᱚᱞᱚᱱ ᱢᱮ",
    adminLoggingIn: "ᱚᱯᱷᱤᱥᱚᱨ ᱯᱚᱨᱠᱷᱟᱣ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
    roleSafetyOfficerTitle: "ᱥᱟᱭᱤᱴ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱚᱯᱷᱤᱥᱚᱨ",
    roleSafetyOfficerDesc: "BCCL / CCL / ECL ᱠᱷᱟᱫᱟᱱ ᱨᱮ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱟᱨ ᱥᱮᱪᱮᱫ ᱧᱮᱞ᱾",
    roleDgmsTitle: "DGMS ᱤᱱᱥᱯᱮᱠᱴᱚᱨ (ᱫᱷᱟᱱᱵᱟᱫᱽ)",
    roleDgmsDesc: "DGMS ᱞᱮᱡᱚᱨ, SHA-256 HMAC ᱥᱟᱠᱟᱢ ᱯᱚᱨᱠᱷᱟᱣ᱾",
    roleStateTitle: "ᱯᱚᱱᱚᱛ ᱱᱚᱰᱟᱞ ᱚᱯᱷᱤᱥᱚᱨ",
    roleStateDesc: "ᱡᱚᱛᱚ ᱡᱤᱞᱟᱹ ᱠᱷᱟᱫᱟᱱ ᱞᱮᱠᱷᱟ ᱟᱨ ᱵᱤᱯᱚᱫᱽ ᱵᱟᱧᱪᱟᱣ ᱧᱮᱞ᱾",
    adminDemoCredsNotice: "ᱰᱮᱢᱳ ᱠᱳᱰ: ᱤᱭᱩᱡᱚᱨ ᱟᱨ ᱯᱟᱥᱣᱟᱨᱰ 'password123'",

    // Common Actions
    startSimulation: "AR ᱥᱮᱪᱮᱫ ᱮᱦᱚᱵ",
    exitSimulation: "ᱥᱮᱪᱮᱫ ᱠᱷᱚᱱ ᱚᱰᱚᱠ",
    nextStep: "ᱞᱟᱦᱟ ᱛᱷᱟᱠ",
    previousStep: "ᱛᱟᱭᱚᱢ",
    finishAssessment: "ᱯᱚᱨᱠᱷᱟᱣ ᱮᱢ",
    viewCertificate: "ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱧᱮᱞ",
    downloadCertificate: "QR ᱥᱟᱠᱟᱢ ᱟᱹᱜᱩᱭ",
    printCertificate: "ᱥᱟᱠᱟᱢ ᱪᱷᱟᱯᱟᱭ ᱢᱮ",
    savePdf: "PDF ᱞᱮᱠᱟᱛᱮ ᱥᱟᱧᱪᱟᱣ",
    returnToPortal: "ᱯᱚᱨᱴᱟᱞ ᱛᱮ ᱨᱩᱣᱟᱹᱲ",
    certificateReadyTitle: "ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱹᱵᱩᱫ ᱥᱟᱠᱟᱢ ᱛᱮᱭᱟᱨ ᱮᱱᱟ",
    certificateReadySubtitle: "A4 ᱯᱷᱚᱨᱢᱟᱴ • ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱨᱮᱠᱳᱨᱰ",
    
    // Worker Portal - E-Identity Card
    workerProfileTitle: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱩᱯᱨᱩᱢ ᱠᱟᱨᱰ",
    activeMinerStatus: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱷᱟᱫᱟᱱ ᱦᱚᱲ",
    workforceCode: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ",
    sectorLabel: "ᱠᱷᱟᱫᱟᱱ ᱛᱷᱚᱠ",
    districtLabel: "ᱡᱤᱞᱟᱹ",
    activeCertsCounter: "DGMS ᱥᱟᱠᱟᱢ ᱠᱚ",
    mandatoryDrillsCounter: "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱥᱮᱪᱮᱫ",
    audioGuidanceBtn: "ᱟᱲᱟᱝ ᱛᱮ ᱟᱸᱡᱚᱢ",

    // Training Modules Section
    modulesSectionTitle: "DGMS ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ AR ᱢᱚᱰᱩᱞ ᱠᱚ",
    modulesSectionSubtitle: "DGMS ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱠᱮᱢᱮᱨᱟ ᱥᱟᱢᱟᱝ ᱨᱮ ᱠᱟᱹᱢᱤ ᱯᱚᱨᱠᱷᱟᱣ ᱥᱮᱪᱮᱫ",
    certifiedBadge: "ᱯᱟᱥ ᱟᱠᱟᱱ",
    statutoryDrillBadge: "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱥᱮᱪᱮᱫ",
    phase2Badge: "ᱫᱚᱥᱟᱨ ᱛᱷᱟᱠ",
    underDgmsSpec: "DGMS ᱛᱮᱭᱟᱨ ᱨᱮ ᱢᱮᱱᱟᱜ-ᱟ",
    passThresholdLabel: "ᱯᱟᱥ ᱢᱟᱨᱠ:",
    
    // 5 Modules Details
    module1Title: "ᱥᱮᱸᱜᱮᱞ ᱟᱨ ᱵᱚᱢ ᱵᱤᱥᱯᱷᱚᱴ ᱵᱟᱧᱪᱟᱣ",
    module1Subtitle: "ᱚᱰᱚᱠᱚᱜ ᱰᱟᱦᱟᱨ ᱯᱟᱱᱛᱷᱟ, ᱥᱮᱸᱜᱮᱞ ᱤᱬᱤᱡ (PASS) ᱠᱟᱹᱢᱤᱦᱚᱨᱟ",
    module1Desc: "ᱠᱮᱢᱮᱨᱟ AR ᱥᱤᱢᱩᱞᱮᱴᱚᱨ: ᱚᱰᱚᱠᱚᱜ ᱰᱟᱦᱟᱨ ᱧᱮᱞ, ᱥᱮᱸᱜᱮᱞ ᱤᱬᱤᱡ ᱯᱤᱱ ᱚᱨ, ᱞᱟᱛᱟᱨ ᱥᱮᱫ ᱴᱷᱤᱠᱟᱹᱭ, ᱦᱮᱱᱰᱮᱞ ᱞᱤᱱ ᱟᱨ CMR 136 ᱞᱮᱠᱟᱛᱮ ᱥᱮᱸᱜᱮᱞ ᱤᱬᱤᱡ᱾",
    module2Title: "ᱜᱮᱥ ᱡᱚᱨᱚ ᱟᱨ ᱪᱤᱯᱟᱹᱴ ᱡᱟᱭᱜᱟ ᱨᱩᱠᱷᱤᱭᱟᱹ",
    module2Subtitle: "ᱢᱤᱛᱷᱮᱱ, CO ᱜᱮᱥ ᱪᱤᱱᱦᱟᱹ, PPE ᱦᱚᱨᱚᱜ ᱟᱨ ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱜᱟᱞᱢᱟᱨᱟᱣ",
    module2Desc: "ᱠᱷᱟᱫᱟᱱ ᱦᱚᱭ ᱜᱮᱥ ᱯᱚᱨᱠᱷᱟᱣ, ᱢᱤᱛᱷᱮᱱ ᱢᱤᱴᱟᱨ ᱧᱮᱞ, SCBA ᱥᱟᱺᱦᱮᱫ ᱢᱟᱥᱠ ᱦᱚᱨᱚᱜ ᱟᱨ ᱵᱟᱨ ᱦᱚᱲ ᱡᱚᱴᱟᱣ (Buddy System) ᱠᱟᱛᱷᱟ ᱯᱩᱥᱴᱟᱹᱣ᱾",
    module3Title: "ᱠᱚᱞ ᱠᱟᱹᱨᱜᱟᱲ ᱟᱨ ᱢᱮᱥᱤᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ",
    module3Subtitle: "ᱠᱚᱱᱵᱷᱮᱭᱟᱨ ᱵᱮᱞᱴ LOTO ᱞᱚᱠ, ᱨᱳᱞᱟᱨ ᱪᱤᱯᱟᱹᱴ ᱟᱨ ᱟᱯᱚᱛᱠᱟᱞᱤᱱ ᱵᱟᱵᱮᱨ",
    module3Desc: "DGMS Circular 2026 ᱞᱮᱠᱟᱛᱮ ᱵᱤᱡᱽᱞᱤ ᱵᱚᱸᱫᱽ ᱠᱟᱛᱮ ᱛᱟᱞᱟ ᱞᱟᱜᱟᱣ (LOTO) ᱟᱨ ᱠᱚᱱᱵᱷᱮᱭᱟᱨ ᱨᱳᱞᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱚᱨᱠᱷᱟᱣ᱾",
    module4Title: "ᱵᱤᱡᱽᱞᱤ ᱟᱨ ᱵᱞᱟᱥᱴᱤᱝ ᱦᱩᱥᱤᱭᱟᱹᱨ",
    module4Subtitle: "FLP ᱵᱤᱡᱽᱞᱤ ᱵᱟᱠᱥᱟ ᱯᱚᱨᱠᱷᱟᱣ, ᱵᱚᱢ ᱥᱟᱯᱲᱟᱣ ᱟᱨ ᱓᱐᱐ ᱢᱤᱴᱚᱨ ᱥᱟᱺᱜᱤᱧ ᱨᱩᱠᱷᱤᱭᱟᱹ",
    module4Desc: "ᱠᱷᱟᱫᱟᱱ ᱵᱤᱡᱽᱞᱤ ᱥᱩᱭᱤᱪ ᱵᱟᱠᱥᱟ ᱜᱮᱯ ᱢᱤᱴᱟᱨ ᱧᱮᱞ ᱟᱨ ᱵᱞᱟᱥᱴᱤᱝ ᱚᱠᱛᱚ ᱓᱐᱐ ᱢᱤᱴᱚᱨ ᱥᱟᱺᱜᱤᱧ ᱨᱮ ᱛᱟᱦᱮᱸᱱ ᱨᱮᱱᱟᱜ ᱟᱹᱱ᱾",
    module5Title: "ᱯᱤᱯᱤᱤ (PPE) ᱦᱚᱨᱚᱜ ᱟᱨ ᱠᱷᱟᱫᱟᱱ ᱵᱚᱞᱚᱱ",
    module5Subtitle: "ᱦᱮᱞᱢᱮᱴ, ᱢᱮᱬᱦᱮᱫ ᱡᱩᱛᱟᱹ, ᱢᱮᱴᱟᱴᱟᱨᱥᱟᱞ ᱜᱟᱨᱰ ᱟᱨ ᱫᱷᱩᱲᱤ ᱢᱟᱥᱠ",
    module5Desc: "ᱠᱮᱢᱮᱨᱟ ᱛᱮ ᱧᱮᱞ ᱠᱟᱛᱮ ᱦᱮᱞᱢᱮᱴ, ᱵᱟᱹᱛᱤ, ᱯᱟᱹᱴᱩᱣᱟᱹ ᱡᱩᱛᱟᱹ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱦᱚᱨᱚᱜ-ᱵᱟᱸᱫᱮ ᱴᱷᱤᱠ ᱢᱮᱱᱟᱜ-ᱟ ᱥᱮ ᱵᱟᱝ ᱯᱚᱨᱠᱷᱟᱣ᱾",
    
    // Passports / Certificates Section
    passportsSectionTitle: "ᱥᱟᱹᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱠᱚ (DGMS ᱥᱮᱪᱮᱫ ᱨᱮᱠᱳᱨᱰ)",
    passportsSectionSubtitle: "Mines Act 1952 ᱞᱮᱠᱟᱛᱮ DGMS ᱥᱟᱹᱨᱤ ᱰᱤᱡᱤᱴᱟᱞ ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱠᱚ᱾",
    certNumberLabel: "ᱥᱟᱠᱟᱢ ᱱᱚᱢᱵᱚᱨ",
    statutoryValidityLabel: "ᱢᱩᱪᱟᱹᱫ ᱢᱟᱹᱦᱤᱛ:",
    noPassportsTitle: "ᱱᱤᱛ ᱫᱷᱟᱹᱵᱤᱡ ᱥᱟᱠᱟᱢ ᱵᱟᱹᱱᱩᱜ-ᱟ",
    noPassportsDesc: "ᱪᱮᱛᱟᱱ ᱨᱮ AR ᱥᱮᱸᱜᱮᱞ ᱟᱨᱵᱟᱝ ᱜᱮᱥ ᱥᱮᱪᱮᱫ ᱯᱩᱨᱟᱹᱣ ᱢᱮ, ᱯᱚᱨᱠᱷᱟᱣ ᱨᱮ ≥ ᱗᱕% ᱱᱚᱢᱵᱚᱨ ᱟᱹᱜᱩᱭ ᱢᱮ, ᱟᱨ ᱟᱢᱟᱜ ᱰᱤᱡᱤᱴᱟᱞ ᱥᱟᱠᱟᱢ ᱱᱚᱰᱮ ᱦᱤᱡᱩᱜ-ᱟ᱾",
    startDrillCta: "AR ᱥᱮᱪᱮᱫ ᱮᱦᱚᱵ ᱢᱮ",

    // AR Fire PASS Steps
    fireHudTitle: "DGMS ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱮᱪᱮᱫ • CMR REG. 136 (PASS DRILL)",
    emergencyExitSign: "ᱚᱰᱚᱠᱚᱜ ᱰᱟᱦᱟᱨ (᱒᱕ ᱢᱤᱴᱚᱨ) →",
    tapToLockAim: "ᱥᱮᱸᱜᱮᱞ ᱵᱩᱴᱟᱹ ᱨᱮ ᱴᱷᱤᱠᱟᱹᱭ ᱞᱟᱹᱜᱤᱫ ᱚᱛᱟᱭ ᱢᱮ",
    passStep0Title: "ᱛᱷᱟᱠ ᱐: ᱚᱰᱚᱠᱚᱜ ᱰᱟᱦᱟᱨ ᱧᱮᱞ ᱢᱮ",
    passStep0Desc: "ᱟᱢ ᱛᱟᱭᱚᱢ ᱨᱮ ᱦᱟᱹᱨᱭᱟᱹᱲ ᱵᱟᱹᱛᱤ ᱚᱰᱚᱠᱚᱜ ᱰᱟᱦᱟᱨ ᱧᱮᱞ ᱢᱮ᱾ ᱞᱟᱦᱟᱜ ᱞᱟᱦᱟ ᱨᱮ ᱰᱟᱦᱟᱨ ᱯᱷᱟᱸᱠᱟ ᱢᱮᱱᱟᱜ-ᱟ ᱥᱮ ᱵᱟᱝ ᱧᱮᱞ ᱢᱮ᱾",
    passStep0Btn: "ᱰᱟᱦᱟᱨ ᱧᱮᱞ ᱮᱱᱟ: ᱞᱟᱦᱟᱜ ᱢᱮ →",
    passP_title: "ᱛᱷᱟᱠ ᱑: ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱤᱱ ᱚᱨ ᱚᱰᱚᱠ (Pull)",
    passP_desc: "ᱥᱤᱞ ᱨᱟᱹᱯᱩᱫ ᱠᱟᱛᱮ ᱦᱮᱱᱰᱮᱞ ᱠᱷᱚᱱ ᱞᱚᱠ ᱯᱤᱱ ᱚᱨ ᱚᱰᱚᱠ ᱢᱮ᱾",
    passP_btn: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱤᱱ ᱚᱨ ᱚᱰᱚᱠ ᱢᱮ →",
    passA_title: "ᱛᱷᱟᱠ ᱒: ᱥᱮᱸᱜᱮᱞ ᱞᱟᱛᱟᱨ ᱨᱮ ᱴᱷᱤᱠᱟᱹᱭ (Aim)",
    passA_desc: "ᱱᱚᱡᱚᱞ ᱫᱚ ᱥᱮᱸᱜᱮᱞ ᱨᱮᱱᱟᱜ ᱵᱩᱴᱟᱹ ᱥᱮᱫ ᱥᱟᱢᱟᱝ ᱢᱮ, ᱫᱷᱩᱶᱟᱹ ᱥᱮᱫ ᱫᱚ ᱵᱟᱝ᱾",
    passA_btn: "ᱥᱮᱸᱜᱮᱞ ᱵᱩᱴᱟᱹ ᱨᱮ ᱴᱷᱤᱠᱟᱹᱭ ᱮᱱᱟ →",
    passS1_title: "ᱛᱷᱟᱠ ᱓: ᱦᱮᱱᱰᱮᱞ ᱞᱤᱱ ᱢᱮ (Squeeze)",
    passS1_desc: "ᱫᱟᱨᱮ ᱜᱩᱸᱰᱟᱹ ᱯᱷᱮᱬ ᱚᱰᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱦᱮᱱᱰᱮᱞ ᱡᱚᱨ ᱛᱮ ᱞᱤᱱ ᱢᱮ᱾",
    passS1_btnHold: "ᱯᱷᱮᱬ ᱚᱰᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱦᱮᱱᱰᱮᱞ ᱞᱤᱱ ᱫᱚᱦᱚᱭ ᱢᱮ",
    passS1_btnRelease: "ᱦᱮᱱᱰᱮᱞ ᱟᱲᱟᱜ ᱢᱮ",
    passS2_title: "ᱛᱷᱟᱠ ᱔: ᱮᱛᱚᱢ ᱠᱚᱧᱮ ᱦᱤᱞᱟᱹᱣ ᱢᱮ (Sweep)",
    passS2_desc: "ᱥᱮᱸᱜᱮᱞ ᱵᱟᱝ ᱤᱬᱤᱡᱚᱜ ᱵᱷᱩᱨ ᱞᱮᱸᱜᱟ ᱟᱨ ᱡᱚᱡᱚᱢ ᱥᱮᱫ ᱦᱤᱞᱟᱹᱣ ᱤᱫᱤ ᱢᱮ᱾",
    passS2_btn: "ᱥᱮᱸᱜᱮᱞ ᱪᱮᱛᱟᱱ ᱨᱮ ᱦᱤᱞᱟᱹᱣ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜ-ᱟ...",
    fireCompleteTitle: "ᱥᱮᱸᱜᱮᱞ ᱯᱩᱨᱟᱹ ᱤᱬᱤᱡ ᱮᱱᱟ!",
    fireCompleteDesc: "ᱟᱢ PASS ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱴᱷᱤᱠ ᱮᱢ ᱯᱩᱨᱟᱹᱣ ᱠᱮᱫ-ᱟ᱾ ᱱᱤᱛᱚᱜ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱢ ᱞᱟᱹᱜᱤᱫ ᱞᱟᱦᱟᱜ ᱢᱮ᱾",
    fireCompleteBtn: "ᱯᱚᱨᱠᱷᱟᱣ ᱮᱦᱚᱵ ᱢᱮ →",

    // AR Gas Module Steps
    gasHudTitle: "DGMS ᱦᱚᱭ ᱜᱮᱥ ᱢᱤᱴᱟᱨ",
    gasDetectTitle: "ᱛᱷᱟᱠ ᱑: ᱦᱚᱭ ᱜᱮᱥ ᱯᱚᱨᱠᱷᱟᱣ",
    gasDetectDesc: "ᱢᱤᱛᱷᱮᱱ (< ᱑.᱒᱕%) ᱟᱨ ᱠᱟᱨᱵᱚᱱ ᱢᱚᱱᱳᱠᱥᱟᱭᱤᱰ (< ᱕᱐ ppm) ᱦᱚᱭ ᱢᱤᱴᱟᱨ ᱧᱮᱞ ᱢᱮ᱾",
    gasDetectBtn: "ᱠᱷᱟᱫᱟᱱ ᱜᱮᱥ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱦᱚᱵ ᱢᱮ →",
    gasAlarmTitle: "ᱟᱹᱱ ᱵᱤᱯᱚᱫᱽ: CMR 142 ᱰᱷᱮᱨ ᱮᱱᱟ",
    gasAlarmDesc: "ᱢᱤᱛᱷᱮᱱ ᱜᱮᱥ ᱑.᱒᱕% ᱠᱷᱚᱱ ᱰᱷᱮᱨ ᱮᱱᱟ᱾ SCBA ᱥᱟᱺᱦᱮᱫ ᱢᱟᱥᱠ ᱵᱟᱝ ᱦᱚᱨᱚᱜ ᱠᱟᱛᱮ ᱞᱟᱦᱟ ᱟᱞᱚᱢ ᱥᱮᱱᱚᱜ-ᱟ᱾",
    gasAlarmBtn: "ᱵᱤᱯᱚᱫᱽ ᱵᱟᱰᱟᱭ ᱮᱱᱟ ᱟᱨ SCBA ᱢᱟᱥᱠ ᱦᱚᱨᱚᱜ ᱢᱮ →",
    gasPpeTitle: "ᱛᱷᱟᱠ ᱒: ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱯᱟᱵ (PPE) ᱦᱚᱨᱚᱜ",
    gasPpeDesc: "ᱥᱟᱺᱦᱮᱫ ᱢᱟᱥᱠ (SCBA), ᱦᱮᱞᱢᱮᱴ ᱵᱟᱹᱛᱤ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱟᱵᱮᱨ ᱦᱚᱨᱚᱜ ᱢᱮ᱾",
    gasPpeBtn: "PPE ᱟᱨ ᱚᱠᱥᱤᱡᱚᱱ ᱵᱟᱠᱥᱟ ᱥᱤᱞ ᱯᱚᱨᱠᱷᱟᱣ ᱢᱮ →",
    gasBuddyTitle: "ᱛᱷᱟᱠ ᱓: ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱜᱟᱞᱢᱟᱨᱟᱣ (Buddy System)",
    gasBuddyDesc: "ᱠᱷᱟᱫᱟᱱ ᱵᱷᱤᱛᱨᱤ ᱵᱚᱞᱚᱱ ᱞᱟᱦᱟ ᱨᱮ ᱵᱟᱦᱨᱮ ᱛᱟᱦᱮᱸᱱ ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱨᱮᱰᱤᱭᱳ ᱛᱮ ᱠᱟᱛᱷᱟ ᱯᱩᱥᱴᱟᱹᱣ ᱢᱮ᱾",
    gasBuddyBtn: "ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱨᱮᱰᱤᱭᱳ ᱠᱟᱛᱷᱟ ᱯᱩᱥᱴᱟᱹᱣ ᱮᱱᱟ →",
    gasCompleteTitle: "ᱜᱮᱥ ᱵᱤᱯᱚᱫᱽ ᱠᱷᱚᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱮᱱᱟ",
    gasCompleteDesc: "DGMS ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱡᱚᱛᱚ ᱦᱚᱭ ᱜᱮᱥ ᱟᱨ ᱡᱚᱴᱟᱣ ᱜᱟᱞᱢᱟᱨᱟᱣ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ᱾",
    gasCompleteBtn: "ᱯᱚᱨᱠᱷᱟᱣ ᱮᱦᱚᱵ ᱢᱮ →",
    sensorOk: "ᱴᱷᱤᱠ",
    sensorCritical: "ᱵᱚᱛᱚᱨ",
    sensorToxic: "ᱵᱤᱥ",
    sensorDeficient: "ᱠᱚᱢ ᱜᱮᱭᱟ",

    // Scenario Quiz
    quizHeader: "DGMS ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱚᱨᱠᱷᱟᱣ",
    questionCounter: "ᱠᱩᱠᱞᱤ",
    ofLabel: "ᱠᱷᱚᱱ",
    complianceBenchmarkNotice: "ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱟᱥ ᱢᱟᱨᱠ: ᱗᱕%",
    selectAnswerPrompt: "ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱡᱟᱦᱟᱸᱱ ᱢᱤᱫ ᱛᱮᱞᱟ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
    submitDecisionBtn: "ᱛᱮᱞᱟ ᱮᱢ ᱢᱮ",
    nextQuestionBtn: "ᱫᱚᱥᱟᱨ ᱠᱩᱠᱞᱤ →",
    quizPassedTitle: "DGMS ᱯᱚᱨᱠᱷᱟᱣ: ᱯᱟᱥ ᱮᱱᱟ (PASSED)",
    quizFailedTitle: "ᱯᱟᱥ ᱢᱟᱨᱠ ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ",
    quizPassedDesc: "Mines Act 1952 ᱞᱮᱠᱟᱛᱮ ᱟᱢ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱚᱨᱠᱷᱟᱣ ᱨᱮᱢ ᱯᱟᱥ ᱮᱱᱟ᱾ ᱰᱤᱡᱤᱴᱟᱞ QR ᱥᱟᱠᱟᱢ ᱵᱮᱱᱟᱣᱜ ᱠᱟᱱᱟ᱾",
    quizFailedDesc: "DGMS ᱞᱮᱠᱟᱛᱮ ᱗᱕% ᱢᱟᱨᱠ ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ᱾ ᱫᱟᱭᱟᱠᱟᱛᱮ ᱟᱨᱦᱚᱸ ᱢᱤᱫ ᱫᱷᱟᱣ ᱥᱮᱪᱮᱫ ᱯᱩᱨᱟᱹᱣ ᱢᱮ᱾",
    scoreAccuracyLabel: "ᱴᱷᱤᱠ ᱛᱮᱞᱟ ᱞᱮᱠᱷᱟ",
    scoreTechniqueLabel: "AR ᱠᱟᱹᱢᱤ ᱱᱚᱢᱵᱚᱨ",
    scoreEvaluationLabel: "ᱢᱩᱪᱟᱹᱫ ᱱᱚᱢᱵᱚᱨ",
    verifiedForIssuance: "✓ DGMS ᱥᱟᱠᱟᱢ ᱮᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱹᱨᱤ ᱮᱱᱟ",
    retakeDrillBtn: "ᱫᱚᱦᱲᱟ ᱥᱮᱪᱮᱫ ᱮᱦᱚᱵ ᱢᱮ",
    generateCertBtn: "ᱥᱟᱠᱟᱢ ᱵᱮᱱᱟᱣ ᱟᱨ ᱧᱮᱞ",
    voiceCorrect: "ᱴᱷᱤᱠ ᱜᱮᱭᱟ!",
    voiceIncorrect: "ᱵᱷᱩᱞ ᱜᱮᱭᱟ᱾ DGMS ᱟᱹᱱ ᱯᱟᱲᱦᱟᱣ ᱢᱮ᱾",

    // Safety Officer Dashboard
    officerDashboardTitle: "ᱥᱟᱭᱤᱴ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱚᱯᱷᱤᱥᱚᱨ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱛᱟᱹᱞᱠᱟᱹ",
    officerSiteSubtitle: "ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱹᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱧᱮᱞ",
    enrolWorkerBtn: "ᱱᱟᱶᱟ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱚᱞ",
    kpiTotalMiners: "ᱡᱚᱛᱚ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ",
    kpiCertifiedRate: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱯᱟᱥ ᱫᱚᱨ",
    kpiPendingDrills: "ᱥᱮᱪᱮᱫ ᱵᱟᱹᱠᱤ ᱦᱚᱲ",
    kpiTribalWorkforce: "ᱥᱟᱱᱛᱟᱲᱤ ᱨᱚᱲ ᱦᱚᱲ",
    searchPlaceholder: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱟᱨᱵᱟᱝ ID ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
    filterAllCohorts: "ᱡᱚᱛᱚ ᱜᱟᱫᱮᱞ (Cohorts)",
    thWorkerId: "ᱠᱟᱹᱢᱤᱭᱟᱹ ID",
    thNameDesig: "ᱧᱩᱛᱩᱢ ᱟᱨ ᱯᱚᱫᱽ",
    thSite: "ᱠᱷᱟᱫᱟᱱ ᱡᱟᱭᱜᱟ",
    thLanguage: "ᱯᱟᱹᱨᱥᱤ",
    thStatus: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱦᱟᱞᱚᱛ",
    thCerts: "ᱥᱟᱹᱵᱩᱫ ᱥᱟᱠᱟᱢ",
    thActions: "ᱠᱟᱹᱢᱤ",
    enrolModalTitle: "ᱱᱟᱶᱟ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱚᱞ",
    enrolModalDesc: "DGMS ᱟᱹᱱ ᱟᱨ ᱯᱟᱹᱨᱥᱤ ᱞᱮᱠᱟᱛᱮ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱥᱮᱞᱮᱫ ᱢᱮ᱾",
    fieldName: "ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ",
    fieldNamePlaceholder: "ᱡᱮᱞᱮᱠᱟ: ᱵᱤᱨᱥᱟ ᱦᱟᱸᱥᱫᱟᱜ",
    fieldLanguage: "ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ",
    fieldDesignation: "ᱠᱟᱹᱢᱤ ᱯᱚᱫᱽ",
    fieldDesignationPlaceholder: "ᱡᱮᱞᱮᱠᱟ: ᱠᱷᱟᱫᱟᱱ ᱰᱨᱤᱞᱟᱨ",
    fieldMobile: "ᱢᱳᱵᱟᱭᱤᱞ ᱱᱚᱢᱵᱚᱨ",
    fieldCohort: "ᱥᱮᱪᱮᱫ ᱜᱟᱫᱮᱞ",
    submitEnrolBtn: "ᱧᱩᱛᱩᱢ ᱚᱞ ᱢᱮ",
    cancelBtn: "ᱵᱟᱹᱜᱤᱭᱟᱜ",

    // DGMS Inspector Portal
    dgmsHeaderTitle: "Directorate General of Mines Safety (DGMS)",
    dgmsHeaderSubtitle: "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱚᱨᱠᱷᱟᱣ ᱴᱟᱨᱢᱤᱱᱟᱞ • ᱫᱷᱟᱱᱵᱟᱫᱽ",
    searchLedgerTitle: "ᱥᱟᱹᱵᱩᱫ ᱥᱟᱠᱟᱢ ᱯᱚᱨᱠᱷᱟᱣ ᱴᱟᱨᱢᱤᱱᱟᱞ",
    searchLedgerDesc: "SHA-256 HMAC ᱦᱮᱥ ᱟᱨᱵᱟᱝ ᱥᱟᱠᱟᱢ ID ᱮᱢ ᱠᱟᱛᱮ ᱥᱚᱨᱠᱟᱨᱤ ᱞᱮᱡᱚᱨ ᱨᱮ ᱯᱚᱨᱠᱷᱟᱣ ᱢᱮ:",
    searchHashPlaceholder: "SHA-256 ᱦᱮᱥ ᱟᱨᱵᱟᱝ ᱥᱟᱠᱟᱢ ID (ᱡᱮᱞᱮᱠᱟ: CERT-JH-2026-10000)",
    verifyBtn: "ᱯᱚᱨᱠᱷᱟᱣ ᱢᱮ",
    kpiAuditedMines: "ᱯᱚᱨᱠᱷᱟᱣ ᱟᱠᱟᱱ ᱠᱷᱟᱫᱟᱱ",
    kpiCryptoPassports: "ᱰᱤᱡᱤᱴᱟᱞ ᱥᱟᱠᱟᱢ ᱠᱚ",
    kpiLedgerIntegrity: "ᱞᱮᱡᱚᱨ ᱥᱟᱹᱨᱤᱭᱟᱹᱛ",
    kpiIntegrityStatus: "100% SHA-256 ᱥᱟᱹᱨᱤ ᱜᱮᱭᱟ",
    kpiViolations: "ᱟᱹᱱ ᱨᱟᱹᱯᱩᱫ ᱞᱮᱠᱷᱟ",
    thCertId: "ᱥᱟᱠᱟᱢ ID",
    thWorker: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ ᱟᱨ ᱧᱩᱛᱩᱢ",
    thModule: "ᱥᱮᱪᱮᱫ ᱢᱚᱰᱩᱞ",
    thScore: "ᱱᱚᱢᱵᱚᱨ",
    thIssueDate: "ᱮᱢ ᱢᱟᱹᱦᱤᱛ",
    thLedgerHash: "ᱞᱮᱡᱚᱨ ᱦᱮᱥ (HMAC-SHA256)",
    thAuditStatus: "ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱦᱟᱞᱚᱛ",
    btnInspect: "ᱨᱮᱠᱳᱨᱰ ᱧᱮᱞ",
    modalAuditTitle: "DGMS ᱞᱮᱡᱚᱨ ᱯᱚᱨᱠᱷᱟᱣ ᱨᱮᱠᱳᱨᱰ",
    modalAuditDesc: "ᱫᱷᱟᱱᱵᱟᱫᱽ ᱢᱩᱬᱩᱛ ᱥᱚᱨᱵᱷᱚᱨ ᱠᱷᱚᱱ ᱥᱟᱹᱨᱤ ᱯᱚᱨᱢᱟᱱ ᱧᱟᱢ ᱮᱱᱟ᱾",
    tamperProofValid: "ᱥᱟᱹᱨᱤ ᱰᱤᱡᱤᱴᱟᱞ ᱥᱤᱜᱽᱱᱮᱪᱟᱨ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱱᱟ",
    btnClose: "ᱵᱚᱸᱫᱽ",

    // State Nodal Dashboard
    stateHeaderTitle: "ᱠᱷᱟᱫᱟᱱ ᱟᱨ ᱵᱷᱩᱛᱚᱛᱣᱚ ᱵᱤᱵᱷᱟᱜᱽ • ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ",
    stateHeaderSubtitle: "ᱯᱚᱱᱚᱛ ᱡᱟᱠᱟᱛ ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱟᱨ AR ᱥᱮᱪᱮᱫ ᱞᱮᱠᱷᱟ",
    kpiTotalWorkforce: "ᱡᱚᱛᱚ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ",
    kpiStateCompliance: "ᱯᱚᱱᱚᱛ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱫᱚᱨ",
    kpiDrillsCompleted: "ᱯᱩᱨᱟᱹᱣ ᱟᱠᱟᱱ AR ᱥᱮᱪᱮᱫ",
    kpiIncidentIndex: "ᱵᱤᱯᱚᱫᱽ ᱵᱟᱧᱪᱟᱣ ᱞᱮᱠᱷᱟ",
    chartDistrictTitle: "ᱡᱤᱞᱟᱹ ᱞᱮᱠᱟᱛᱮ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱫᱚᱨ",
    chartLanguageTitle: "AR ᱥᱮᱪᱮᱫ ᱨᱮ ᱯᱟᱹᱨᱥᱤ ᱵᱮᱵᱷᱟᱨ",
    chartModuleTitle: "ᱢᱚᱰᱩᱞ ᱞᱮᱠᱟᱛᱮ ᱥᱮᱪᱮᱫ ᱫᱟᱲᱮ",
    thDistrict: "ᱡᱤᱞᱟᱹ",
    thSector: "ᱠᱷᱟᱫᱟᱱ ᱛᱷᱚᱠ",
    thMinesCount: "ᱪᱟᱹᱞᱩ ᱠᱷᱟᱫᱟᱱ ᱠᱚ",
    thEnrolledMiners: "ᱥᱮᱞᱮᱫ ᱠᱟᱹᱢᱤᱭᱟᱹ",
    thDistrictRate: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱫᱚᱨ",
    thDistrictStatus: "ᱟᱹᱱ ᱦᱟᱞᱚᱛ",
    exportReportBtn: "ᱯᱚᱱᱚᱛ ᱨᱤᱯᱳᱨᱴ ᱰᱟᱣᱩᱱᱞᱳᱰ (CSV / PDF)",

    // Global Footer
    footerLinkHome: "ᱢᱩᱬᱩᱛ ᱥᱟᱦᱴᱟ",
    footerLinkSimulator: "ᱥᱤᱢᱩᱞᱮᱴᱚᱨ ᱵᱟᱰᱟᱭ",
    footerLinkCurriculum: "ᱥᱮᱪᱮᱫ ᱢᱚᱰᱮᱞ",
    footerLinkRti: "RTI ᱵᱟᱰᱟᱭ",
    footerLinkEvaluation: "ᱯᱚᱨᱠᱷᱟᱣ ᱜᱟᱫᱮᱞ",
    footerLinkActs: "ᱟᱹᱱ ᱟᱨ ᱱᱤᱭᱚᱢ",
    footerLinkSafety: "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱮᱵᱚᱥᱛᱟ",
    footerLinkScreenReader: "ᱥᱠᱨᱤᱱ ᱯᱟᱲᱦᱟᱣ",
    footerLinkOfficialLogin: "ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱞᱚᱜᱤᱱ",
    footerDeptTitle: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ • ᱠᱷᱟᱫᱟᱱ ᱟᱨ ᱵᱷᱩᱛᱚᱛᱣᱚ ᱵᱤᱵᱷᱟᱜᱽ",
    footerDeptDesc: "DGMS ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱠᱷᱟᱫᱟᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱱᱟᱣ ᱟᱠᱟᱱ AR ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱤᱢᱩᱞᱮᱴᱚᱨ᱾",
    footerDgmsTitle: "DGMS ᱨᱩᱠᱷᱤᱭᱟᱹ ᱟᱹᱱ ᱢᱟᱱᱚᱠ",
    footerDgmsDesc: "Mines Act 1952 ᱟᱨ Coal Mines Regulations 2017 ᱞᱮᱠᱟᱛᱮ ᱵᱤᱯᱚᱫᱽ ᱠᱷᱚᱱ ᱵᱟᱧᱪᱟᱣ᱾",
    footerSihTitle: "Smart India Hackathon 2026 ᱥᱮᱪᱮᱫ ᱱᱚᱢᱩᱱᱟ",
    footerSihDesc: "Problem Statement 26041 ᱞᱟᱹᱜᱤᱫ ᱵᱮᱱᱟᱣ ᱟᱠᱟᱱᱟ᱾ ᱡᱚᱛᱚ ᱨᱮᱠᱳᱨᱰ ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱠᱟᱱᱟ᱾",
    footerCopyright: "© ᱒᱐᱒᱖ ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ ᱟᱨ DGMS ᱫᱷᱟᱱᱵᱟᱫᱽ᱾ SIH 2026 ᱞᱟᱹᱜᱤᱫ ᱴᱮᱠᱱᱤᱠᱟᱞ ᱱᱚᱢᱩᱱᱟ᱾",

    // Audio Prompts
    audioPullPin: "ᱥᱮᱸᱜᱮᱞ ᱤᱬᱤᱡ ᱥᱟᱯᱟᱵ ᱨᱮᱱᱟᱜ ᱯᱤᱱ ᱚᱨ ᱚᱰᱚᱠ ᱢᱮ᱾",
    audioAimBase: "ᱱᱚᱡᱚᱞ ᱫᱚ ᱥᱮᱸᱜᱮᱞ ᱞᱟᱛᱟᱨ ᱥᱮᱫ ᱴᱷᱤᱠᱟᱹᱭ ᱢᱮ᱾",
    audioSqueezeLever: "ᱯᱷᱮᱬ ᱚᱰᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱦᱮᱱᱰᱮᱞ ᱡᱚᱨ ᱛᱮ ᱞᱤᱱ ᱢᱮ᱾",
    audioSweepFire: "ᱞᱮᱸᱜᱟ ᱟᱨ ᱡᱚᱡᱚᱢ ᱥᱮᱫ ᱦᱤᱞᱟᱹᱣ ᱢᱮ᱾",
    audioGasAlarm: "ᱵᱚᱛᱚᱨ! ᱵᱤᱥ ᱜᱮᱥ ᱰᱷᱮᱨ ᱮᱱᱟ᱾ ᱥᱟᱺᱦᱮᱫ ᱢᱟᱥᱠ ᱩᱥᱟᱹᱨᱟ ᱦᱚᱨᱚᱜ ᱢᱮ!",
    audioBuddyConfirm: "ᱠᱷᱟᱫᱟᱱ ᱵᱚᱞᱚᱱ ᱞᱟᱦᱟ ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱨᱮᱰᱤᱭᱳ ᱛᱮ ᱜᱟᱞᱢᱟᱨᱟᱣ ᱢᱮ᱾",

    // Additional Gas Module keys
    gasHudAuditNotice: "DGMS ᱟᱹᱱ ᱢᱤᱴᱟᱨ: ᱦᱚᱭ ᱜᱮᱥ ᱚᱰᱤᱴ",
    gasAlarmNotice: "DGMS ᱵᱤᱯᱚᱫᱽ: ᱜᱮᱥ ᱥᱤᱢᱟᱹ ᱯᱟᱨᱚᱢ ᱮᱱᱟ (CMR 142)",
    gasHeadingLabel: "DGMS ᱠᱷᱟᱫᱟᱱ ᱥᱩᱨᱩᱝ #᱓ • ᱦᱚᱭ ᱜᱮᱥ ᱢᱤᱴᱟᱨ ᱪᱟᱹᱞᱩ",
    gasMethaneLimit: "CH₄ (DGMS <᱑.᱒᱕%):",
    gasCoLimit: "CO (DGMS <᱕᱐ppm):",
    gasOxygenLimit: "O₂ (DGMS ᱑᱙.᱕-᱒᱑%):",
    gasPpeVerifyPrompt: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱞᱮᱠᱟᱛᱮ ᱥᱟᱱᱟᱢ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱯᱟᱵ ᱯᱚᱨᱠᱷᱟᱣ ᱢᱮ:",
    gasPpeMask: "᱑. ᱯᱚᱡᱤᱴᱤᱵᱷ-ᱯᱨᱮᱥᱟᱨ SCBA ᱥᱟᱺᱦᱮᱫ ᱢᱟᱥᱠ",
    gasPpeFitMask: "[ᱢᱟᱥᱠ ᱦᱚᱨᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱚᱛᱟᱭ ᱢᱮ]",
    gasPpeHelmet: "᱒. ᱵᱟᱹᱛᱤ ᱥᱟᱶ ᱦᱮᱞᱢᱮᱴ",
    gasPpeLockHelmet: "[ᱦᱮᱞᱢᱮᱴ ᱞᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱚᱛᱟᱭ ᱢᱮ]",
    gasPpeHarness: "᱓. ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱟᱵᱮᱨ ᱥᱟᱶ ᱦᱟᱨᱱᱮᱥ",
    gasPpeAttachLifeline: "[ᱵᱟᱵᱮᱨ ᱡᱚᱲᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱚᱛᱟᱭ ᱢᱮ]",
    gasPpeProceedBtn: "PPE ᱯᱚᱨᱠᱷᱟᱣ ᱮᱱᱟ • ᱡᱚᱴᱟᱣ ᱥᱟᱹᱜᱟᱹᱭ ᱧᱮᱞ ᱢᱮ →",
    gasPpeRequiredPrompt: "ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱯᱮᱭᱟ ᱥᱟᱯᱟᱵ ᱜᱮ ᱦᱚᱨᱚᱜ ᱢᱮ",
    gasBuddyReqPrompt: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱫᱷᱟᱨᱟ ᱒᱒ ᱞᱮᱠᱟᱛᱮ ᱵᱟᱦᱨᱮ ᱡᱚᱴᱟᱣ ᱥᱟᱶ ᱥᱟᱹᱜᱟᱹᱭ ᱞᱟᱹᱠᱛᱤᱭᱟ:",
    gasBuddyRadio: "ᱨᱮᱰᱤᱭᱳ ᱥᱟᱹᱜᱟᱹᱭ ᱯᱚᱨᱠᱷᱟᱣ (ᱪᱮᱱᱟᱞ ᱔)",
    gasBuddyCheckRadio: "[ᱥᱤᱜᱽᱱᱟᱞ ᱧᱮᱞ ᱢᱮ]",
    gasBuddyLifeline: "ᱵᱟᱵᱮᱨ ᱚᱨ ᱟᱹᱱ (᱒ ᱫᱷᱟᱣ = ᱴᱷᱤᱠ, ᱓ ᱫᱷᱟᱣ = ᱵᱤᱯᱚᱫᱽ)",
    gasBuddyConfirmLifeline: "[ᱚᱨ ᱯᱩᱥᱴᱟᱹᱣ ᱢᱮ]",
    gasBuddyRequiredPrompt: "ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱡᱚᱴᱟᱣ ᱟᱹᱱ ᱯᱩᱨᱟᱹᱣ ᱢᱮ",
    gasProtocolSuccessVoice: "ᱟᱹᱱ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱱᱟ᱾ ᱠᱷᱟᱫᱟᱱ ᱵᱚᱞᱚᱱ ᱪᱷᱟᱹᱲ ᱧᱟᱢ ᱮᱱᱟ᱾",

    // Additional Scenario Quiz keys
    quizAssessmentTitle: "DGMS ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱵᱤᱰᱟᱹᱣ",
    quizPaperSub: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ • ᱵᱤᱰᱟᱹᱣ ᱥᱟᱠᱟᱢ",
    quizCorrectDecision: "ᱴᱷᱤᱠ ᱟᱹᱱ ᱜᱚᱴᱟ",
    quizViolation: "DGMS ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱟᱹᱲᱤᱡ",
    quizViewResultsBtn: "ᱵᱤᱰᱟᱹᱣ ᱚᱨᱡᱚ ᱧᱮᱞ ᱢᱮ →",
    quizNextBtn: "ᱛᱟᱭᱚᱢ ᱠᱩᱠᱞᱤ →",
    quizSubmitBtn: "ᱛᱮᱞᱟ ᱮᱢ ᱢᱮ ᱟᱨ ᱵᱤᱰᱟᱹᱣ ᱢᱮ →",

    // Certificate Top Bar keys
    certActionBarTitle: "ᱟᱹᱱ ᱞᱮᱠᱟᱛᱮ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱠᱟᱢ ᱥᱟᱯᱲᱟᱣ ᱮᱱᱟ",
    certA4Format: "A4 ᱪᱷᱟᱯᱟ ᱜᱚᱲᱦᱚᱱ",
    certOfficialRecord: "ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱚᱞ",
    saveAsPdf: "PDF ᱨᱮ ᱥᱟᱧᱪᱟᱣ ᱢᱮ",

    // Safety Officer Dashboard keys
    officerStationTitle: "ᱟᱹᱱ ᱧᱮᱞ-ᱛᱚᱫᱟᱨᱚᱠ ᱛᱷᱟᱱ",
    officerDistrict: "ᱡᱤᱞᱟᱹ",
    officerSector: "ᱴᱚᱴᱷᱟ",
    officerSupervisoryOfficer: "ᱧᱮᱞ-ᱛᱚᱫᱟᱨᱚᱠ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ",
    officerStationSub: "DGMS ᱟᱹᱱ ᱪᱮᱫᱚᱜ ᱛᱷᱟᱱ #᱔",
    officerOnboardRecruit: "ᱱᱟᱶᱟ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱥᱮᱞᱮᱫ ᱢᱮ",
    officerCohortBatch: "ᱪᱮᱫᱚᱜ ᱡᱟᱣᱨᱟ ᱵᱮᱪ",
    officerEnrolledMiners: "ᱥᱮᱞᱮᱫ ᱟᱠᱟᱱ",
    officerMinersLabel: "ᱠᱟᱹᱢᱤᱭᱟᱹ",
    officerCertifiedMiners: "ᱥᱟᱠᱟᱢ ᱧᱟᱢ",
    officerRosterTitle: "ᱞᱟᱦᱟ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱞᱤᱥᱴᱤ ᱟᱨ DGMS ᱥᱟᱠᱟᱢ ᱦᱟᱞᱚᱛ",
    officerRosterSubtitle: "ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱯᱟᱹᱨᱥᱤ, ᱚᱞ-ᱯᱟᱲᱦᱟᱣ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱠᱟᱢ ᱦᱟᱞᱚᱛ ᱧᱮᱞ",
    officerSearchPlaceholder: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ ᱥᱮ ID ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
    officerAllCohorts: "ᱥᱟᱱᱟᱢ ᱪᱮᱫᱚᱜ ᱵᱮᱪ",
    officerThWorkerCode: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ",
    officerThFullName: "ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ",
    officerThTribalLang: "ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱯᱟᱹᱨᱥᱤ",
    officerThLiteracy: "ᱚᱞ-ᱯᱟᱲᱦᱟᱣ",
    officerThDesignation: "ᱠᱟᱹᱢᱤ ᱯᱚᱫᱽ",
    officerThActiveCerts: "ᱪᱟᱹᱞᱩ ᱥᱟᱠᱟᱢ",
    officerThStatus: "ᱟᱹᱱ ᱦᱟᱞᱚᱛ",
    officerCompliantBadge: "DGMS ᱢᱟᱱᱟᱣ ᱟᱠᱟᱱ",
    officerTrainingDueBadge: "ᱪᱮᱫᱚᱜ ᱵᱟᱹᱠᱤ",
    officerDrillsCount: "ᱵᱤᱰᱟᱹᱣ",
    officerBestScore: "ᱥᱚᱨᱮᱥ",
    officerModalTitle: "ᱱᱟᱶᱟ ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱥᱮᱞᱮᱫ ᱢᱮ",
    officerModalSubtitle: "ᱠᱮᱢᱮᱨᱟ AR ᱪᱮᱫᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱚᱞ ᱥᱮᱞᱮᱫ ᱢᱮ᱾",
    officerFieldFullName: "ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ (ᱯᱟᱹᱨᱤᱥ ᱥᱟᱶ):",
    officerFieldPrimaryLang: "ᱢᱩᱬᱩᱛ ᱯᱟᱹᱨᱥᱤ:",
    officerFieldDesignation: "ᱠᱟᱹᱢᱤ ᱯᱚᱫᱽ:",
    officerFieldContact: "ᱯᱷᱳᱱ ᱱᱚᱢᱵᱚᱨ:",
    officerFieldAssignCohort: "ᱪᱮᱫᱚᱜ ᱵᱮᱪ ᱨᱮ ᱴᱷᱟᱶ ᱮᱢ:",
    officerBtnCancel: "ᱵᱟᱹᱛᱤᱞ",
    officerBtnSubmitEnroll: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱥᱮᱞᱮᱫ ᱢᱮ ᱟᱨ AR ᱢᱳᱰᱩᱞ ᱮᱢᱟᱭ ᱢᱮ",

    // DGMS Portal keys
    dgmsConsoleBadge: "ᱟᱹᱱ ᱵᱤᱰᱟᱹᱣ ᱠᱚᱱᱥᱳᱞ",
    dgmsBenchmarkSub: "DGMS ᱢᱟᱱᱚᱠ ᱠᱚᱱᱥᱳᱞ • ᱫᱷᱟᱱᱵᱟᱫᱽ ᱟᱹᱱ ᱜᱟᱸᱴᱷᱟᱣ",
    dgmsLedgerTitle: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱢᱟᱱᱟᱣ ᱵᱟᱦᱤ (DGMS ᱟᱹᱱ ᱵᱤᱰᱟᱹᱣ)",
    dgmsAuditorLabel: "ᱵᱤᱰᱟᱹᱣᱤᱡ / ᱧᱮᱞᱤᱡ",
    dgmsBenchmarkRef: "ᱟᱹᱱ ᱥᱟᱹᱠᱷᱤ: DGMS/S&T/Circular-2026/041",
    dgmsExportCsv: "ᱟᱹᱱ ᱚᱰᱤᱴ ᱵᱟᱦᱤ ᱰᱟᱣᱩᱱᱞᱳᱰ (CSV)",
    dgmsScannerTitle: "ᱞᱟᱭᱤᱵᱷ QR ᱥᱟᱠᱟᱢ ᱯᱚᱨᱠᱷᱟᱣ ᱟᱨ ᱡᱟᱞ ᱥᱮᱸᱫᱽᱨᱟ ᱥᱠᱮᱱᱟᱨ",
    dgmsScannerDesc: "ᱞᱟᱭᱤᱵᱷ ᱵᱟᱦᱤ ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱟᱨᱰ QR ᱥᱠᱮᱱ ᱢᱮ ᱥᱮ ᱥᱟᱠᱟᱢ ID / Hash ᱚᱞ ᱢᱮ",
    dgmsInputPlaceholder: "QR Hash ᱥᱮ ᱥᱟᱠᱟᱢ ID ᱱᱚᱸᱰᱮ ᱚᱞ ᱢᱮ...",
    dgmsVerifying: "DGMS ᱵᱟᱦᱤ ᱛᱚᱞᱟᱥᱚᱜ ᱠᱟᱱᱟ...",
    dgmsVerifyBtn: "ᱥᱟᱹᱨᱤᱭᱟᱹᱛ ᱯᱚᱨᱠᱷᱟᱣ ᱢᱮ →",
    dgmsTestValid: "ᱴᱷᱤᱠ ᱥᱟᱠᱟᱢ ᱵᱤᱰᱟᱹᱣ",
    dgmsTestForgery: "ᱡᱟᱞ ᱥᱟᱠᱟᱢ ᱵᱤᱰᱟᱹᱣ",
    dgmsVerifiedAuthentic: "ᱥᱟᱹᱨᱤ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱱᱟ: DGMS ᱟᱹᱱ ᱢᱟᱱᱟᱣ ᱟᱠᱟᱱ",
    dgmsFraudDetected: "ᱨᱮᱠᱚᱨᱰ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ ᱥᱮ ᱡᱟᱞ ᱥᱟᱠᱟᱢ ᱠᱟᱱᱟ",
    dgmsVerifiedDetail: "SHA-256 HMAC ᱥᱩᱦᱤ ᱯᱚᱨᱠᱷᱟᱣ ᱮᱱᱟ᱾ ᱪᱮᱫ ᱦᱚᱸ ᱵᱟᱝ ᱵᱚᱫᱚᱞ ᱟᱠᱟᱱᱟ᱾",
    dgmsFraudDetail: "ᱮᱢ ᱟᱠᱟᱱ QR hash ᱫᱚ ᱨᱮᱠᱚᱨᱰ ᱥᱟᱶ ᱵᱟᱝ ᱢᱤᱞᱟᱹᱣᱜ ᱠᱟᱱᱟ᱾",
    dgmsWorkerDetails: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱵᱤᱵᱚᱨᱚᱱ",
    dgmsMineFacility: "ᱠᱷᱟᱫᱟᱱ ᱴᱷᱟᱶ",
    dgmsModuleCompetency: "ᱢᱳᱰᱩᱞ ᱦᱩᱱᱟᱹᱨ",
    dgmsValidityWindow: "ᱟᱹᱱ ᱪᱟᱹᱞᱩ ᱚᱠᱛᱚ",
    dgmsPassedTag: "ᱱᱚᱢᱵᱚᱨ: {score}% (ᱯᱟᱥ)",
    dgmsExpiresLabel: "ᱢᱩᱪᱟᱹᱫ ᱢᱟᱹᱦᱤᱛ",
    dgmsRefresherDays: "ᱢᱟᱦᱟᱸ ᱫᱚᱦᱲᱟ ᱪᱮᱫᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱹᱠᱤ",
    dgmsViewPrintCert: "ᱥᱟᱠᱟᱢ ᱧᱮᱞ ᱟᱨ ᱪᱷᱟᱯᱟᱭ ᱢᱮ",
    dgmsAuditRegisterTitle: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱟᱹᱱ ᱚᱰᱤᱴ ᱨᱮᱡᱤᱥᱴᱟᱨ",
    dgmsAuditRegisterDesc: "ᱥᱟᱱᱟᱢ ᱮᱢ ᱟᱠᱟᱱ ᱥᱟᱠᱟᱢ ᱟᱨ cryptographic hash ᱨᱮᱭᱟᱜ ᱰᱤᱡᱤᱴᱟᱞ ᱵᱟᱦᱤ",
    dgmsFilterSector: "ᱴᱚᱴᱷᱟ ᱞᱮᱠᱟᱛᱮ ᱵᱟᱪᱷᱟᱣ:",
    dgmsSectorAll: "ᱥᱟᱱᱟᱢ ᱠᱟᱹᱨᱜᱟᱲ ᱴᱚᱴᱷᱟ",
    dgmsSectorCoal: "ᱠᱩᱭᱞᱟᱹ ᱠᱷᱟᱫᱟᱱ (BCCL / CCL)",
    dgmsSectorSteel: "ᱢᱮᱬᱦᱮᱫ ᱠᱟᱹᱨᱜᱟᱲ (SAIL / Tata)",
    dgmsSectorMica: "ᱢᱟᱭᱠᱟ ᱠᱟᱹᱨᱜᱟᱲ (ᱠᱳᱰᱟᱨᱢᱟ / ᱜᱤᱨᱤᱰᱤᱦ)",
    dgmsThCertId: "ᱥᱟᱠᱟᱢ ID",
    dgmsThWorkerCode: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ",
    dgmsThWorkerName: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ",
    dgmsThMineSite: "ᱠᱷᱟᱫᱟᱱ / ᱠᱟᱹᱨᱜᱟᱲ",
    dgmsThDistrict: "ᱡᱤᱞᱟᱹ",
    dgmsThScore: "ᱱᱚᱢᱵᱚᱨ",
    dgmsThIssueDate: "ᱮᱢ ᱢᱟᱹᱦᱤᱛ",
    dgmsThExpiryDate: "ᱢᱩᱪᱟᱹᱫ ᱢᱟᱹᱦᱤᱛ",
    dgmsThStatus: "ᱟᱹᱱ ᱦᱟᱞᱚᱛ",
    dgmsThVerify: "ᱯᱚᱨᱠᱷᱟᱣ",
    dgmsBtnAudit: "ᱚᱰᱤᱴ",
    dgmsBtnPrint: "ᱪᱷᱟᱯᱟ",
    dgmsClosePreview: "✕ ᱧᱮᱞ ᱵᱚᱸᱫᱽ ᱢᱮ",

    // State Nodal Dashboard keys
    stateConsoleBadge: "ᱯᱚᱱᱚᱛ ᱱᱳᱰᱟᱞ ᱞᱮᱠᱷᱟ",
    stateConsoleSub: "ᱥᱮᱪᱮᱫ ᱵᱤᱰᱟᱹᱣ ᱠᱚᱱᱥᱳᱞ • ᱠᱷᱟᱫᱟᱱ ᱵᱤᱵᱷᱟᱜᱽ (ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ) ᱞᱮᱠᱟᱛᱮ",
    stateMainTitle: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ — ᱯᱚᱱᱚᱛ ᱞᱮᱠᱷᱟ ᱟᱨ ᱟᱹᱱ ᱵᱤᱰᱟᱹᱣ",
    stateOfficerLine: "ᱯᱚᱱᱚᱛ ᱱᱳᱰᱟᱞ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ",
    stateSandboxNotice: "ᱴᱮᱠᱱᱤᱠᱟᱞ ᱵᱤᱰᱟᱹᱣ • ᱞᱟᱭᱤᱵᱷ ᱟᱹᱱ ᱞᱮᱠᱷᱟ",
    stateFrameworkTag: "ᱟᱹᱱ ᱜᱟᱸᱴᱷᱟᱣ: ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ (DGMS ᱪᱤᱴᱷᱤ)",
    stateKpiCertified: "ᱥᱟᱱᱟᱢ ᱥᱟᱠᱟᱢ ᱧᱟᱢ ᱠᱟᱹᱢᱤᱭᱟᱹ",
    stateKpiGrowth: "↑ ᱑᱘.᱔% ᱪᱟᱸᱫᱚ-ᱪᱟᱸᱫᱚ ᱵᱟᱹᱲᱛᱤ",
    stateKpiPassRate: "ᱥᱟᱱᱟᱢ ᱯᱟᱥ ᱦᱤᱥᱟᱹᱵᱽ",
    stateKpiDgmsBenchmark: "DGMS ᱢᱟᱱᱚᱠ: ᱗᱕%",
    stateKpiActiveSites: "ᱪᱟᱹᱞᱩ ᱠᱷᱟᱫᱟᱱ ᱴᱷᱟᱶ",
    stateKpiUnits: "ᱠᱩᱭᱞᱟᱹ, ᱢᱮᱬᱦᱮᱫ ᱟᱨ ᱢᱟᱭᱠᱟ ᱴᱷᱟᱶ",
    stateKpiRefresherDue: "ᱫᱚᱦᱲᱟ ᱪᱮᱫᱚᱜ ᱵᱟᱹᱠᱤ (<᱓᱐ ᱢᱟᱦᱟᱸ)",
    stateKpiNoticeIssued: "ᱥᱟᱭᱤᱴ ᱟᱹᱢᱟᱹᱞᱤᱭᱟᱹ ᱠᱚ ᱱᱳᱴᱤᱥ ᱮᱢ ᱮᱱᱟ",
    stateChart1Title: "ᱡᱤᱞᱟᱹ ᱞᱮᱠᱟᱛᱮ ᱦᱟᱯᱛᱟᱠᱤᱭᱟᱹ ᱥᱟᱠᱟᱢ ᱮᱞ",
    stateChart1Sub: "ᱫᱷᱟᱱᱵᱟᱫᱽ, ᱵᱚᱠᱟᱨᱳ, ᱨᱟᱢᱜᱚᱲ ᱟᱨ ᱠᱳᱰᱟᱨᱢᱟ ᱨᱮ ᱞᱟᱦᱟᱱᱛᱤ",
    stateChart2Title: "AR ᱪᱮᱫᱚᱜ ᱨᱮ ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱯᱟᱹᱨᱥᱤ ᱦᱟᱹᱴᱤᱧ",
    stateChart2Sub: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚᱣᱟᱜ ᱨᱚᱲ ᱟᱨ ᱚᱞ ᱵᱮᱵᱷᱟᱨ ᱦᱟᱹᱴᱤᱧ",
    stateRadarTitle: "ᱟᱹᱱ ᱓᱐ ᱢᱟᱦᱟᱸ ᱥᱟᱠᱟᱢ ᱢᱩᱪᱟᱹᱫ ᱦᱩᱥᱤᱭᱟᱹᱨ ᱨᱟᱰᱟᱨ",
    stateRadarSub: "ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱥᱮᱨᱢᱟᱠᱤᱭᱟᱹ ᱪᱮᱫᱚᱜ ᱞᱟᱹᱠᱛᱤᱭᱟ᱾ ᱓᱐ ᱢᱟᱦᱟᱸ ᱨᱮ ᱢᱩᱪᱟᱹᱫᱚᱜ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱛᱟᱨ ᱨᱮ ᱢᱮᱱᱟᱜ ᱠᱚᱣᱟ᱾",
    stateActionRequired: "ᱥᱟᱭᱤᱴ ᱧᱮᱞᱤᱡ ᱠᱚ ᱠᱟᱹᱢᱤ ᱦᱩᱭᱩᱜ-ᱟ",
    stateThCertId: "ᱥᱟᱠᱟᱢ ID",
    stateThWorkerCode: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱳᱰ",
    stateThWorkerName: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ",
    stateThContactPhone: "ᱯᱷᱳᱱ ᱱᱚᱢᱵᱚᱨ",
    stateThMineSite: "ᱠᱷᱟᱫᱟᱱ ᱴᱷᱟᱶ",
    stateThIssueDate: "ᱮᱢ ᱢᱟᱹᱦᱤᱛ",
    stateThExpiryDate: "ᱟᱹᱱ ᱢᱩᱪᱟᱹᱫ",
    stateThStatus: "ᱦᱟᱞᱚᱛ",
    stateRefresherDueBadge: "⚠ ᱫᱚᱦᱲᱟ ᱪᱮᱫᱚᱜ ᱵᱟᱹᱠᱤ",
    stateAllCompliant: "ᱥᱟᱱᱟᱢ ᱟᱹᱱ ᱥᱟᱠᱟᱢ ᱱᱤᱛᱚᱜ ᱴᱷᱤᱠ ᱚᱠᱛᱚ ᱨᱮ ᱢᱮᱱᱟᱜ-ᱟ᱾",

    // Extended Footer keys
    footerDeptTitleText: "ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ (PS ID: ᱒᱖᱐᱔᱑)",
    footerDeptSubText: "AR ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱪᱮᱫᱚᱜ ᱤᱧᱡᱤᱱ",
    footerDeptBodyText: "ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ ᱞᱟᱹᱜᱤᱫ ᱥᱮᱪᱮᱫ ᱴᱮᱠᱱᱤᱠᱟᱞ ᱯᱨᱳᱴᱳᱴᱟᱭᱤᱯ᱾ ᱠᱷᱟᱫᱟᱱ ᱵᱤᱵᱷᱟᱜᱽ (ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ) ᱟᱨ ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱟᱨ DGMS ᱢᱟᱱᱚᱠ ᱞᱮᱠᱟᱛᱮ ᱵᱮᱱᱟᱣ ᱟᱠᱟᱱᱟ᱾",
    footerStandardsTitleText: "ᱢᱟᱱᱚᱠ ᱟᱨ ᱫᱤᱥᱟᱹ-ᱩᱫᱩᱜ",
    footerStd1Text: "• DGMS ᱠᱷᱟᱫᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱢᱟᱱᱚᱠ",
    footerStd2Text: "• ᱠᱷᱟᱫᱟᱱ ᱟᱹᱱ ᱑᱙᱕᱒ ᱟᱨ ᱠᱟᱹᱨᱜᱟᱲ ᱟᱹᱱ ᱑᱙᱔᱘",
    footerStd3Text: "• ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ — PS ID: ᱒᱖᱐᱔᱑",
    footerStd4Text: "• ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱫᱤᱥᱟᱹ-ᱩᱫᱩᱜ (GIGW 3.0 / WCAG 2.1 AA)",
    footerDevTitleText: "ᱵᱮᱱᱟᱣ ᱟᱨ ᱥᱮᱪᱮᱫ ᱩᱫᱩᱜ",
    footerDevByText: "SIH ᱒᱐᱒᱖ ᱴᱤᱢ ᱦᱚᱛᱮᱛᱮ ᱵᱮᱱᱟᱣ ᱟᱠᱟᱱᱟ (PS ID: ᱒᱖᱐᱔᱑)",
    footerDevSubText: "ᱠᱷᱟᱫᱟᱱ ᱟᱨ ᱢᱮᱬᱦᱮᱫ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱪᱮᱫᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱥᱮᱪᱮᱫ ᱯᱨᱳᱴᱳᱴᱟᱭᱤᱯ",
    footerDrillCountText: "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱵᱤᱰᱟᱹᱣ ᱞᱮᱠᱷᱟ:",
    footerLegalDisclaimerText: "ᱟᱹᱱ ᱦᱩᱥᱤᱭᱟᱹᱨ: ᱱᱚᱶᱟ ᱫᱚ ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱒᱐᱒᱖ (PS ID: ᱒᱖᱐᱔᱑) ᱞᱟᱹᱜᱤᱫ ᱢᱤᱫ ᱥᱮᱪᱮᱫ ᱴᱮᱠᱱᱤᱠᱟᱞ ᱯᱨᱳᱴᱳᱴᱟᱭᱤᱯ ᱠᱟᱱᱟ᱾ ᱱᱚᱶᱟ ᱫᱚ ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ ᱥᱮ DGMS ᱥᱮ NIC ᱨᱮᱭᱟᱜ ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱯᱳᱨᱴᱟᱞ ᱫᱚ ᱵᱟᱝ ᱠᱟᱱᱟ᱾",
    footerCopyrightNoticeText: "ᱥᱟᱱᱟᱢ ᱟᱹᱱ ᱧᱩᱛᱩᱢ ᱟᱨ ᱢᱟᱱᱚᱠ ᱫᱚ ᱵᱷᱟᱨᱚᱛ ᱠᱚᱯᱤᱨᱟᱭᱤᱴ ᱟᱹᱱ ᱑᱙᱕᱗ ᱨᱮᱭᱟᱜ ᱫᱷᱟᱨᱟ ᱕᱒ ᱞᱮᱠᱟᱛᱮ ᱦᱮᱯᱨᱟᱣ ᱟᱨ ᱥᱮᱪᱮᱫ ᱩᱫᱩᱜ ᱞᱟᱹᱜᱤᱫ ᱜᱮ ᱵᱮᱵᱷᱟᱨ ᱟᱠᱟᱱᱟ᱾"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('jh_safety_lang') || 'en';
  });
  const [audioEnabled, setAudioEnabled] = useState(true);
  const [isSpeaking, setIsSpeaking] = useState(false);

  useEffect(() => {
    localStorage.setItem('jh_safety_lang', language);
    // Broadcast language change to window so any component or custom event listener updates
    try {
      window.dispatchEvent(new CustomEvent('jh-language-changed', { detail: { language } }));
    } catch (e) {
      console.warn('Language event dispatch note:', e);
    }
  }, [language]);

  // Safe translation accessor proxy that falls back to English, then to key itself
  const currentDict = translations[language] || translations.en;
  const t = new Proxy(currentDict, {
    get(target, prop) {
      if (prop in target && target[prop] !== undefined && target[prop] !== '') {
        return target[prop];
      }
      if (translations.en && prop in translations.en) {
        return translations.en[prop];
      }
      return prop;
    }
  });

  const speak = (text) => {
    if (!audioEnabled || !('speechSynthesis' in window)) return;
    try {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      
      if (language === 'hi') {
        utterance.lang = 'hi-IN';
        utterance.rate = 0.9;
      } else if (language === 'sat') {
        utterance.lang = 'hi-IN'; // Phonetic synthesis for Indic script
        utterance.rate = 0.85;
      } else {
        utterance.lang = 'en-IN';
        utterance.rate = 0.95;
      }

      utterance.onstart = () => setIsSpeaking(true);
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);

      window.speechSynthesis.speak(utterance);
    } catch (err) {
      console.warn('Speech synthesis error:', err);
      setIsSpeaking(false);
    }
  };

  const stopSpeaking = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    setIsSpeaking(false);
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      audioEnabled,
      setAudioEnabled,
      isSpeaking,
      speak,
      stopSpeaking
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
